Repository ca-cwds/cans, pull requests merged in 2018-12, with the labels that each got.

#331 Update Rails for security patches
  Gemfile
  Gemfile.lock
Labels: patch

#328 CANS-605 shared redis session gem
  Gemfile
  Gemfile.lock
  config/initializers/session_store.rb
  lib/infrastructure/cwds_authenticator.rb
  lib/infrastructure/timeout_middleware.rb
  spec/lib/infrastructure/timeout_middleware_spec.rb
Labels: minor

#338 Set dev Procfile making it easy to run in dev mode
  Gemfile
  Procfile.dev
  README.md
  package.json
Labels: patch

#364 Initial commit for SemVer for PR and master
  Jenkinsfile
Labels: patch

#366 Patch: URL fixing for AssessmentHistory serial components updating
  app/javascript/Application/components/Client/AddCansLink.js
  app/javascript/Application/components/Client/AddCansLink.test.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistory.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryRecord.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryTable.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryTableLink.js
  app/javascript/Application/components/common/AssessmentLink.js
  app/javascript/Application/components/common/AssessmentRecordInfo.js
Labels: patch

#368 Fit 349 implement semantic ver for cans
  Jenkinsfile
Labels: patch

#365 Cans 867 ie comment accordion alignment fix
  app/javascript/Application/components/Assessment/Domain.js
  app/javascript/Application/components/Assessment/Domain.test.js
  app/javascript/Application/components/Assessment/Item.js
  app/javascript/Application/components/Assessment/style.sass
Labels: patch

#346 CANS-605 shared redis session
  Gemfile
  Gemfile.lock
  config/initializers/session_store.rb
  lib/infrastructure/cwds_authenticator.rb
  lib/infrastructure/security_policy.rb
  lib/infrastructure/timeout_middleware.rb
  spec/lib/infrastructure/security_policy_spec.rb
  spec/lib/infrastructure/timeout_middleware_spec.rb
Labels: minor

#367 Update Change Log page with Assessment Date in title;
  app/javascript/Application/components/Assessment/ChangeLog/AssessmentChangeLog.js
  app/javascript/Application/components/Assessment/ChangeLog/AssessmentChangeLog.test.js
  app/javascript/Application/components/Assessment/ChangeLog/ChangeLogHelper.js
  app/javascript/Application/components/Assessment/ChangeLog/ChangeLogHelper.test.js
  app/javascript/Application/components/Assessment/ChangeLog/ChangeLogLoadingBoundary.js
  app/javascript/Application/components/Assessment/ChangeLog/ChangeLogLoadingBoundary.test.js
  app/javascript/Application/components/Assessment/ChangeLog/ChangeLogPage.js
  app/javascript/Application/components/Assessment/ChangeLog/ChangeLogPage.test.js
  app/javascript/Application/components/Assessment/ChangeLog/PrintChangeLog.js
  app/javascript/Application/components/Assessment/ChangeLog/PrintChangeLog.test.js
  app/javascript/Application/components/Assessment/assessment.mocks.test.js
  app/javascript/Application/components/Assessment/style.sass
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryTableEllipsis.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryTableEllipsis.test.js
  app/javascript/Application/components/common/AssessmentRecordInfo.js
  app/javascript/Application/components/common/AssessmentRecordInfo.test.js
  app/javascript/Application/components/common/Ellipsis.js
  app/javascript/Application/components/common/Ellipsis.test.js
  spec/acceptance/assessment_page_spec.rb
Labels: minor

#370 CANS-664 Success Messages for v1.1
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/style.sass
  app/javascript/Application/util/constants.js
  spec/acceptance_helpers/resource_helper.rb
Labels: minor

#373 Make all the Assessment History Table columns sortable; Use created_t…
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryTable.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryTable.test.js
  app/javascript/Application/components/common/AssessmentLink.js
  app/javascript/Application/components/common/AssessmentLink.test.js
Labels: minor

#372 CANS-198 A CANS assessment in a completed status cannot be edited
  .eslintrc.js
  app/javascript/Application/components/Assessment/Assessment.js
  app/javascript/Application/components/Assessment/Assessment.test.js
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader.test.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConductedByField.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConductedByField.test.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/HasCaregiverQuestion.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/HasCaregiverQuestion.test.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/UnderSixQuestion.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/UnderSixQuestion.test.js
  app/javascript/Application/components/Assessment/CompleteAssessmentButton.js
  app/javascript/Application/components/Assessment/Domain.js
  app/javascript/Application/components/Assessment/Domain.test.js
  app/javascript/Application/components/Assessment/DomainCommentAccordion.js
  app/javascript/Application/components/Assessment/DomainCommentAccordion.test.js
  app/javascript/Application/components/Assessment/DomainItemList.js
  app/javascript/Application/components/Assessment/DomainItemList.test.js
  app/javascript/Application/components/Assessment/Item.js
  app/javascript/Application/components/Assessment/Item.test.js
  app/javascript/Application/components/Assessment/ItemBooleanRating.js
  app/javascript/Application/components/Assessment/ItemBooleanRating.test.js
  app/javascript/Application/components/Assessment/ItemDescriptionRating.js
  app/javascript/Application/components/Assessment/ItemDescriptionRating.test.js
  app/javascript/Application/components/Assessment/ItemNaCheckbox.js
  app/javascript/Application/components/Assessment/ItemNaCheckbox.test.js
  app/javascript/Application/components/Assessment/ItemRegularRating.js
  app/javascript/Application/components/Assessment/ItemRegularRating.test.js
  app/javascript/Application/components/Assessment/ItemStyling.js
  app/javascript/Application/components/Assessment/style.sass
  app/javascript/Application/components/Layout/style.sass
  app/javascript/Application/components/common/Comment.js
  app/javascript/Application/components/common/Comment.test.js
  app/javascript/Application/components/common/DateField.js
Labels: minor

#371 Update fetch method in Change Log Loading Boundary; Update AssessmentCha…
  app/javascript/Application/components/Assessment/ChangeLog/AssessmentChangeLog.js
  app/javascript/Application/components/Assessment/ChangeLog/AssessmentChangeLog.test.js
  app/javascript/Application/components/Assessment/ChangeLog/ChangeLogLoadingBoundary.js
  app/javascript/Application/components/Assessment/ChangeLog/ChangeLogPage.test.js
  app/javascript/Application/components/Assessment/ChangeLog/PrintChangeLog.js
  app/javascript/Application/components/Assessment/ChangeLog/PrintChangeLog.test.js
  spec/acceptance_helpers/resource_helper.rb
Labels: minor

#376 CANS-811 View Only Mode for "In Progress" CANS assessment
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/style.sass
Labels: minor

#379 CANS-646 Text added to Non-Case Carrying's view of Dashboard
  app/javascript/Application/components/Search/SearchContainer.js
  app/javascript/Application/components/Search/SearchContainer.test.js
Labels: minor

#377 CANS-664 Update styles for tooltip hover text
  app/javascript/Application/components/Assessment/style.sass
Labels: minor

#380 Patch: re-adjust the complete auto scroll destination
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
Labels: patch

#378 CANS-841: Reference Age Template above the domain headers
  app/javascript/Application/components/Assessment/AssessmentCard.js
  app/javascript/Application/components/Assessment/AssessmentCard.test.js
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/style.sass
  app/javascript/Application/styles/global/cwds-conflict-fixes.sass
Labels: minor

#383 CANS-198 A CANS assessment in a completed status cannot be edited
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
Labels: patch

#375 CANS-825 Added alert message when closing browser tab and window
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  spec/acceptance/assessment_page_spec.rb
Labels: minor

#381 Remove Add CANS link when disabled
  app/javascript/Application/components/Assessment/ChangeLog/AssessmentChangeLog.js
  app/javascript/Application/components/Client/AddCansLink.js
  app/javascript/Application/components/Client/AddCansLink.test.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistory.test.js
Labels: minor

#385 CANS-716 Update Assessment History Links and Change Log title;
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Assessment/ChangeLog/AssessmentChangeLog.js
  app/javascript/Application/components/Assessment/ChangeLog/AssessmentChangeLog.test.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistory.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistory.test.js
  app/javascript/Application/components/Search/SearchAssessmentHistory.js
  app/javascript/Application/components/common/AssessmentLink.js
  app/javascript/Application/components/common/AssessmentLink.test.js
Labels: minor

#382 CANS-860. IE Browser - Page does not get back to the top after all the save messages disappear
  app/javascript/Application/components/common/GlobalAlert.js
  app/javascript/Application/util/common.js
Labels: patch

#384 CANS-852: Change log breadcrumbs
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Assessment/AssessmentHelper.test.js
  app/javascript/Application/components/Assessment/ChangeLog/ChangeLogPage.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistory.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistory.test.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryRecord.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryRecord.test.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryTable.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryTable.test.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryTableEllipsis.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryTableEllipsis.test.js
  app/javascript/Application/components/Client/Client.js
  app/javascript/Application/components/Client/Client.test.js
  app/javascript/Application/components/Layout/BreadCrumb/BreadCrumbHelper.js
  app/javascript/Application/components/Layout/BreadCrumb/BreadCrumbPipeline.js
  app/javascript/Application/components/Layout/BreadCrumb/BreadCrumbPipeline.test.js
  app/javascript/Application/components/Layout/BreadCrumb/BreadCrumbsBuilder.js
  app/javascript/Application/components/Layout/BreadCrumb/BreadCrumbsBuilder.test.js
  app/javascript/Application/components/Layout/PageContentSwitcher.js
  app/javascript/Application/components/Layout/PageContentSwitcher.test.js
  app/javascript/Application/components/Search/SearchAssessmentHistory.js
  app/javascript/Application/components/Search/SearchAssessmentHistory.test.js
  app/javascript/Application/components/Search/SearchAssessmentHistoryRecord.js
  app/javascript/Application/components/Search/SearchAssessmentHistoryRecord.test.js
  app/javascript/Application/components/Search/SearchContainer.js
  app/javascript/Application/components/Search/SearchContainer.test.js
  app/javascript/Application/components/common/AssessmentRecordInfo.js
  app/javascript/Application/components/common/AssessmentRecordInfo.test.js
  app/javascript/Application/components/common/Ellipsis.js
  app/javascript/Application/components/common/Ellipsis.test.js
  app/javascript/Application/routes/Routes.js
  app/javascript/Application/routes/Routes.test.js
  app/javascript/Application/routes/SearchRoutes.js
  app/javascript/Application/util/constants.js
  app/javascript/Application/util/urlTrimmer.js
  app/javascript/Application/util/urlTrimmer.test.js
Labels: minor

#386 CANS-841: "not selected age" bug fix
  app/javascript/Application/components/Assessment/AssessmentCard.js
  app/javascript/Application/components/Assessment/AssessmentCard.test.js
Labels: bug, patch

#387 CANS-664 Success Messages for v1.1
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Assessment/AssessmentHelper.test.js
  app/javascript/Application/components/Header/PageHeader.js
  app/javascript/Application/components/Layout/Page.js
  app/javascript/Application/components/Layout/style.sass
  app/javascript/Application/components/common/GlobalAlert.js
  app/javascript/Application/components/common/GlobalAlert.test.js
  app/javascript/Application/util/GlobalAlertService.js
  app/javascript/Application/util/GlobalAlertService.test.js
Labels: bug, patch

#388 Patch: Breadcrumbs supervisor flow bug fix for CANS-852
  app/javascript/Application/components/Layout/BreadCrumb/BreadCrumbHelper.js
  app/javascript/Application/components/Layout/BreadCrumb/BreadCrumbPipeline.js
  app/javascript/Application/components/Layout/BreadCrumb/BreadCrumbsBuilder.test.js
Labels: bug, patch

#353 Cans 150 expand or collapse domains
  app/javascript/Application/components/Assessment/Assessment.js
  app/javascript/Application/components/Assessment/Assessment.test.js
  app/javascript/Application/components/Assessment/AssessmentCard.js
  app/javascript/Application/components/Assessment/AssessmentCard.test.js
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/Domain.js
  app/javascript/Application/components/Assessment/Domain.test.js
  app/javascript/Application/components/Assessment/DomainsHeader.js
  app/javascript/Application/components/Assessment/DomainsHeader.test.js
  app/javascript/Application/components/Assessment/style.sass
  app/javascript/Application/styles/global/colors.sass
Labels: minor

#389 Add MS only css rule to auto hide scroll bars in the Assessment Histo…
  app/javascript/Application/components/Client/style.sass
Labels: patch

#391 CANS-877. CANS Reminder Date Refactored
  app/javascript/Application/components/Client/ClientSocialWorkerCardTemplate.js
  app/javascript/Application/components/Client/ClientSocialWorkerCardTemplateHelper.js
  app/javascript/Application/components/Client/ClientSocialWorkerCardTemplateHelper.test.js
Labels: patch

#390 CANS-902 Fixed Timeout warning to appear 5 mins prior user session expiration
  app/javascript/Application/util/TimeoutService.js
  app/javascript/Application/util/TimeoutService.test.js
Labels: patch

#394 CANS-857 Rework AuthBoundary front end component to use metadata permissions instead of Security API
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/AssessmentFormFooter.js
  app/javascript/Application/components/Assessment/AssessmentFormFooter.test.js
  app/javascript/Application/components/Assessment/assessment.mocks.test.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistory.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistory.test.js
  app/javascript/Application/components/Client/Client.js
  app/javascript/Application/components/common/AuthBoundary.js
  app/javascript/Application/components/common/AuthBoundary.test.js
  app/javascript/Application/components/common/AuthHelper.js
  app/javascript/Application/components/common/AuthHelper.test.js
  docker-compose.ci.yml
  docker-compose.yml
Labels: minor
