Repository ca-cwds/cans, pull requests merged in 2019-01, with the labels that each got.

#397 CANS-883 Update CANS Printed Version of the Assessment Form
  app/javascript/Application/components/Assessment/assessment.mocks.test.js
  app/javascript/Application/components/Print/PrintAssessment.js
  app/javascript/Application/components/Print/PrintAssessment.test.js
  app/javascript/Application/components/Print/PrintAssessmentStyle.js
  app/javascript/Application/components/Print/PrintSummary.js
  app/javascript/Application/components/Search/Autocomplete/SearchResults/AgeInfo.test.js
Labels: minor

#396 CANS-875: county on Client profile now populated from Client.county field instead of Client.counties
  app/javascript/Application/components/Client/Client.js
  app/javascript/Application/components/Client/Client.test.js
Labels: patch

#398 CANS-857 Cleanup of AssessmentContainer from SecurityService calls
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
Labels: patch

#405 Lock bundler to version 1.x (Maybe a temporary fix?)
  docker/test/Dockerfile
Labels: patch

#400 CANS-908 Placeholder added in client search
  app/javascript/Application/components/Search/ClientSearch/QueryInput/InputField.js
  app/javascript/Application/components/Search/ClientSearch/QueryInput/InputField.test.js
Labels: minor

#407 CANS-883 Fix font style
  app/javascript/Application/components/Assessment/assessment.mocks.test.js
  app/javascript/Application/components/Print/PrintAssessmentStyle.js
Labels: patch

#402 CANS-879 fix styles and wording
  app/javascript/Application/components/Assessment/AssessmentFormHeader/UnderSixQuestion.js
  app/javascript/Application/components/common/AssessmentRecordInfo.js
  app/javascript/Application/components/common/AssessmentRecordInfo.test.js
  app/javascript/Application/styles/global/cwds-conflict-fixes.sass
  package.json
  yarn.lock
Labels: minor

#409 CANS-897: regression test for Staging environment
  Jenkinsfile
Labels: patch

#411 CANS-915 regression test script for Case worker login and Assessment in process.
  spec/acceptance_helpers/resource_helper.rb
  spec/regression/case_worker_login_spec.rb
  spec/regression/index_page_spec.rb
Labels: minor

#410 CANS-918 Regression test for Assessment Form completion of age 0 to 5
  .gitignore
  spec/acceptance_helper.rb
  spec/acceptance_helpers/create_in_process_form_helper.rb
  spec/acceptance_helpers/form_completion_helper.rb
  spec/regression/form_completion_0_to_5_spec.rb
Labels: minor

#415 Regression tests refactoring
  spec/acceptance/assessment_page_spec.rb
  spec/acceptance_helper.rb
  spec/acceptance_helpers/resource_helper.rb
  spec/regression/case_worker_login_spec.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: patch

#418 Use react-widgets custom build with proper casing
  package.json
  yarn.lock
Labels: patch

#416 CANS-922: Add Dora and Elasticsearch to Docker Compose file to run CANS in "bubble" during PR build
  docker-compose.ci.yml
  docker-compose.yml
  spec/acceptance/index_page_spec.rb
  spec/acceptance/search_page_spec.rb
  spec/acceptance_helpers/login_helper.rb
Labels: patch

#414 CANS-913-SupervisorLoginRegressionTest
  spec/acceptance_helper.rb
  spec/acceptance_helpers/resource_helper.rb
  spec/regression/case_worker_scenarios_spec.rb
  spec/regression/supervisor_login_spec.rb
Labels: minor

#417 Remove hidden column from CAH table;
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryTable.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryTable.test.js
Labels: patch

#419 Refactor SAH Loading Boundary
  app/javascript/Application/components/Search/AssessmentHistory/SearchAssessmentHistoryLoadingBoundary.js
  app/javascript/Application/components/Search/AssessmentHistory/SearchAssessmentHistoryLoadingBoundary.test.js
  app/javascript/Application/components/Search/SearchContainer.js
Labels: patch

#423 Missing test case scenarios.
  spec/acceptance_helpers/resource_helper.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: patch

#422 CANS-927 Breadcrumb link is allowing the user to access deleted assessment bug fixing up
  app/javascript/Application/components/Layout/BreadCrumb/BreadCrumbPipeline.js
  app/javascript/Application/components/Layout/BreadCrumb/BreadCrumbsBuilder.js
  app/javascript/Application/components/Layout/BreadCrumb/BreadCrumbsBuilder.test.js
  app/javascript/Application/components/common/Ellipsis.js
  app/javascript/Application/components/common/Ellipsis.test.js
  app/javascript/Application/routes/Routes.js
  app/javascript/Application/routes/Routes.test.js
  app/javascript/Application/routes/SearchRoutes.js
  app/javascript/Application/routes/SearchRoutes.test.js
Labels: patch

#421 Remove unnecessary Ellipsis menu item props and optimize Ellipsis tests;
  app/javascript/Application/components/common/Ellipsis.js
  app/javascript/Application/components/common/Ellipsis.test.js
Labels: patch

#424 Fix docker-compose file
  docker-compose.yml
Labels: patch

#425 CANS-879 - (Pagination styles) IE and Edge require a min-width and a width
  app/javascript/Application/styles/global/cwds-conflict-fixes.sass
Labels: patch

#426 Including site_prism gem
  Gemfile
  Gemfile.lock
  legal/licenses.csv
  spec/acceptance_helper.rb
Labels: patch

#429 CANS-916 Assessment form header, domain, and item common functionalities regression test
  spec/acceptance_helper.rb
  spec/acceptance_helpers/form_completion_helper.rb
  spec/page_objects/assessment_form.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: minor

#428 CANS-897: Staging regression test Jenkins file added
  Jenkinsfile_staging_regression.groovy
  spec/acceptance_helpers/prod_login_helper.rb
Labels: patch

#431 CANS-942 Breadcrumb is wrong after click on ADD CANS link
  Gemfile.lock
  app/javascript/Application/components/Client/AddCansLink.js
  app/javascript/Application/components/Client/AddCansLink.test.js
  app/javascript/Application/components/Layout/BreadCrumb/BreadCrumbsBuilder.test.js
Labels: patch

#430 CANS-914 Regression test - Non Case worker
  spec/page_objects/client_search.rb
  spec/regression/non_case_worker_scenarios_spec.rb
Labels: patch

#432 CANS-936: Session inactivity time-out (4 hrs.) is not functionning as intended.
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/util/TimeoutService.js
  app/javascript/Application/util/TimeoutService.test.js
Labels: bug, patch

#434 CANS-932. Improve performance for Read Staff Latest Assessments operation
  app/javascript/Application/components/Assessment/Assessment.service.js
  app/javascript/Application/components/Assessment/Assessment.service.test.js
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Assessment/AssessmentHelper.test.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistory.js
  app/javascript/Application/components/Search/AssessmentHistory/SearchAssessmentHistory.js
  app/javascript/Application/components/Search/AssessmentHistory/SearchAssessmentHistory.test.js
  app/javascript/Application/components/Search/AssessmentHistory/SearchAssessmentHistoryLoadingBoundary.js
  app/javascript/Application/components/Search/SearchContainer.js
  app/javascript/Application/components/Search/search.mocks.js
  config/routes.rb
  lib/staff/staff_repository.rb
  spec/lib/staff/staff_repository_spec.rb
Labels: major

#436 CANS-917-Caregiver domain Testing
  spec/acceptance_helper.rb
  spec/page_objects/assessment_form.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: patch

#437 CANS-930: test reporting added to acceptance tests and staging regression test
  Jenkinsfile
  Jenkinsfile_staging_regression.groovy
  spec/regression/supervisor_login_spec.rb
Labels: patch

#438 CANS-919 Assessment form completion for age 6 to 21 regression test
  spec/acceptance_helper.rb
  spec/acceptance_helpers/create_in_process_form_helper.rb
  spec/page_objects/assessment_form.rb
  spec/page_objects/breadcrumbs.rb
  spec/page_objects/client_list.rb
  spec/page_objects/client_profile.rb
  spec/regression/case_worker_scenarios_spec.rb
  spec/regression/supervisor_login_spec.rb
Labels: minor

#439 CANS-725 - Fix eslint warnings
  .eslintrc.js
  app/javascript/Application/components/Assessment/DomainProgressBar.js
  app/javascript/Application/components/Assessment/ItemBooleanRating.js
  app/javascript/Application/components/Assessment/ItemNaCheckbox.js
  app/javascript/Application/components/Assessment/ItemRegularRating.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryTable.js
  app/javascript/Application/components/Client/Client.js
  app/javascript/Application/components/Client/ClientAddEditForm.js
  app/javascript/Application/components/Client/ClientFormValidator.js
  app/javascript/Application/components/Client/ClientSocialWorkerCard.js
  app/javascript/Application/components/Layout/BreadCrumb/BreadCrumbsBuilder.js
  app/javascript/Application/components/Search/ClientSearch/QueryResults/SuggestionHeader.js
  app/javascript/Application/components/Staff/StaffTable.js
  app/javascript/Application/components/Staff/Supervisor/SubordinateLoadingBoundary.js
  app/javascript/Application/components/Staff/Supervisor/SubordinateLoadingBoundary.test.js
  app/javascript/Application/enums/AddressType.js
  app/javascript/Application/enums/SystemCodes.js
  app/javascript/Application/util/ApiErrorHandler.js
  app/javascript/Application/util/DataGridHelper.js
  app/javascript/Application/util/DataGridHelper.test.js
  app/javascript/Application/util/assessmentAutoScroll.js
  app/javascript/Application/util/formatters.js
Labels: patch

#440 added acceptanceTestStage back into master build.
  Jenkinsfile
Labels: patch

#442 CANS-787 Empty rows on last page of pagination in supervisor dashboard
  app/javascript/Application/components/Client/ClientSocialWorkerCard.js
  app/javascript/Application/components/Client/ClientSocialWorkerCard.test.js
  app/javascript/Application/components/Staff/StaffTable.js
  app/javascript/Application/components/Staff/StaffTable.test.js
  app/javascript/Application/components/Staff/staff.mocks.test.js
  app/javascript/Application/util/DataGridHelper.js
  app/javascript/Application/util/DataGridHelper.test.js
Labels: bug, patch

#443 CANS-725 - Item Rating refactor
  app/javascript/Application/components/Assessment/Item/Item.js
  app/javascript/Application/components/Assessment/Item/Item.test.js
  app/javascript/Application/components/Assessment/Item/ItemBooleanRating.js
  app/javascript/Application/components/Assessment/Item/ItemBooleanRating.test.js
  app/javascript/Application/components/Assessment/Item/ItemDescriptionRating.js
  app/javascript/Application/components/Assessment/Item/ItemDescriptionRating.test.js
  app/javascript/Application/components/Assessment/Item/ItemNaCheckbox.js
  app/javascript/Application/components/Assessment/Item/ItemNaCheckbox.test.js
  app/javascript/Application/components/Assessment/Item/ItemRating.js
  app/javascript/Application/components/Assessment/Item/ItemRating.test.js
  app/javascript/Application/components/Assessment/Item/ItemRegularRating.js
  app/javascript/Application/components/Assessment/Item/ItemRegularRating.test.js
  app/javascript/Application/components/Assessment/Item/ItemStyling.js
  app/javascript/Application/components/Assessment/Item/ItemStyling.test.js
  app/javascript/Application/components/Assessment/Item/RatingHelper.js
  app/javascript/Application/components/Assessment/Item/RatingHelper.test.js
  app/javascript/Application/components/Assessment/Item/index.js
  app/javascript/Application/components/Assessment/ItemRegularRating.js
  app/javascript/Application/components/Assessment/index.js
  app/javascript/Application/util/ratingHelper.js
Labels: patch

#445 CANS-920 Delete and Change Log test and regression test for Case worker refactor
  spec/acceptance_helpers/resource_helper.rb
  spec/page_objects/assessment_form.rb
  spec/page_objects/client_profile.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: patch

#447 Update readme.md
  resources/docs/newrelic/readme.md
Labels: patch

#446 CANS-901: When user navigates away from a view-only assessment, the navigation warning message will NOT appear
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/assessment.mocks.test.js
Labels: patch

#448 FIT-423 changed checkoutStage to call sh with sudo for removing workspace
  Jenkinsfile
Labels: patch

#449 Acceptance test in PreInt fix
  Jenkinsfile
Labels: patch

#450 Revert "CANS-901: When user navigates away from a view-only assessment, the navigation warning message will NOT appear"
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/assessment.mocks.test.js
Labels: patch

#451 Patch for (CANS-787) staff or client list "with pagination" has extra empty rows bug fixing
  app/javascript/Application/components/Client/ClientSocialWorkerCard.test.js
  app/javascript/Application/components/Staff/StaffTable.test.js
  app/javascript/Application/util/DataGridHelper.js
  app/javascript/Application/util/DataGridHelper.test.js
Labels: patch

#452 CANS-901: When user navigates away from a view-only assessment, the navigation warning message will NOT appear
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/assessment.mocks.test.js
Labels: patch

#453 CANS-944-RefactorRegressionSuiteForPOMCompliance
  spec/acceptance_helper.rb
  spec/acceptance_helpers/resource_helper.rb
  spec/page_objects/assessment_changelog.rb
  spec/page_objects/assessment_form.rb
  spec/page_objects/client_list.rb
  spec/page_objects/client_profile.rb
  spec/page_objects/client_search.rb
  spec/page_objects/sections/app_globals.rb
  spec/page_objects/sections/breadcrumbs.rb
  spec/page_objects/staff_dashboard.rb
  spec/page_objects/supervisor_dashboard.rb
  spec/regression/case_worker_scenarios_spec.rb
  spec/regression/non_case_worker_scenarios_spec.rb
  spec/regression/supervisor_login_spec.rb
Labels: patch

#454 Change eslint warnings to errors
  .eslintrc.js
Labels: patch

#455 Add a release toggle for CANS 2.0
  app/javascript/Application/util/features.js
  app/javascript/Application/util/features.test.js
  app/views/layouts/application.html.erb
  config/feature.yml
  spec/acceptance/index_page_spec.rb
Labels: minor

#456 Code 139 cleanup deadcode
  app/javascript/Application/components/Client/ClientAddEditForm.js
  app/javascript/Application/components/Client/ClientAddEditForm.test.js
  app/javascript/Application/components/Client/ClientFormValidator.js
  app/javascript/Application/components/Client/ClientFormValidator.test.js
  app/javascript/Application/components/Client/index.js
  app/javascript/Application/components/Client/style.sass
  app/javascript/Application/components/Layout/BreadCrumb/BreadCrumbHelper.js
  app/javascript/Application/components/Layout/PageContentSwitcher.js
  app/javascript/Application/components/Layout/PageContentSwitcher.test.js
  app/javascript/Application/components/index.js
  app/javascript/Application/routes/Routes.js
  app/javascript/Application/routes/Routes.test.js
  app/javascript/Application/util/constants.js
Labels: patch

#460 CANS-957: Minor bug: Change a word in pop up
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
Labels: bug, patch

#458 CANS-958: switch to regression tests during PR
  Jenkinsfile
  Jenkinsfile_staging_regression.groovy
  docker-compose.ci.yml
  package.json
  run-regression-test.sh
  spec/acceptance/assessment_page_spec.rb
  spec/acceptance/client_page_spec.rb
  spec/acceptance/index_page_spec.rb
  spec/acceptance/search_page_spec.rb
  spec/acceptance_helper.rb
  spec/acceptance_helpers/login_helper.rb
  spec/acceptance_helpers/resource_helper.rb
  spec/page_objects/client_profile.rb
  spec/regression/case_worker_scenarios_spec.rb
  spec/regression/index_page_spec.rb
  spec/regression/non_case_worker_scenarios_spec.rb
  spec/regression/supervisor_login_spec.rb
Labels: patch

#461 CANS-964 - Remove/Add Caregiver links
  app/javascript/Application/components/Assessment/Domain.test.js
  app/javascript/Application/components/Assessment/DomainCaregiverControls.js
  app/javascript/Application/components/Assessment/DomainCaregiverControls.test.js
  app/javascript/Application/components/Assessment/style.sass
  spec/page_objects/assessment_form.rb
Labels: patch

#467 Fix regression 'Case worker creates and deletes assessment' scenario
  Jenkinsfile
  spec/page_objects/client_profile.rb
Labels: patch

#469 Quick fix to verify that a recently deleted
  spec/page_objects/assessment_changelog.rb
  spec/page_objects/client_profile.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: patch

#466 CANS-958: rename regression test phase for PreInt
  Jenkinsfile
Labels: patch

#468 CANS-951 Require a delete reason on Modal Popup
  app/javascript/Application/components/Assessment/AssessmentActionsEllipsis.js
  app/javascript/Application/components/Assessment/AssessmentActionsEllipsis.test.js
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/AssessmentDeleteModal.js
  app/javascript/Application/components/Assessment/AssessmentDeleteModal.test.js
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Assessment/AssessmentRecordInfo.js
  app/javascript/Application/components/Assessment/style.sass
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryTable.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryTable.test.js
  app/javascript/Application/components/common/Comment.js
  app/javascript/Application/components/common/Comment.test.js
  app/javascript/Application/components/common/ConfidentialityWarning.js
  app/javascript/Application/components/common/ConfidentialityWarning.test.js
  app/javascript/Application/components/common/PageModal.js
  app/javascript/Application/components/common/PageModal.test.js
  app/javascript/Application/components/common/style.sass
  app/javascript/Application/styles/global/colors.sass
  spec/page_objects/sections/app_globals.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: minor

#471 Hotfix pipeline for CANS
  Jenkinsfile
Labels: patch

#464 CANS-966-Summary Card Available before Assessment Completes
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/AssessmentSummary/AssessmentSummaryCard.js
  app/javascript/Application/components/Assessment/AssessmentSummary/AssessmentSummaryCard.test.js
  spec/regression/case_worker_scenarios_spec.rb
Labels: minor

#457 CANS-909 Fix Caregiver Domain Shows Previous Domain's Name
  app/javascript/Application/components/Assessment/Assessment.js
  app/javascript/Application/components/Assessment/Assessment.test.js
Labels: bug, patch

#463 CANS-923: Update webpack-dev-server dependency
  package.json
  yarn.lock
Labels: patch

#477 Revert "CANS-923: Update webpack-dev-server dependency"
  package.json
  yarn.lock
Labels: patch

#479 SNAP-847 Updated Dora Api gem
  Gemfile
  Gemfile.lock
Labels: minor

#475 CANS-962 Increased ellipsis size to 2x
  app/javascript/Application/components/Assessment/AssessmentActionsEllipsis.js
  app/javascript/Application/components/Assessment/AssessmentActionsEllipsis.test.js
Labels: minor
