Repository ca-cwds/cans, pull requests merged in 2019-02, with the labels that each got.

#473 CANS-948 Status appears in assessment history table
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Assessment/AssessmentHelper.test.js
  app/javascript/Application/components/Assessment/AssessmentRecordStatus.js
  app/javascript/Application/components/Assessment/AssessmentRecordStatus.test.js
  app/javascript/Application/components/Assessment/style.sass
  app/javascript/Application/components/Client/AssessmentHistory/AssessmentHistoryTableHelper.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryTable.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryTable.test.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryTableStatus.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryTableStatus.test.js
Labels: minor

#480 Patch: font style fixing and state refine for CANS-951 AssessmentDeleteModal
  app/javascript/Application/components/Assessment/AssessmentDeleteModal.js
  app/javascript/Application/components/Assessment/AssessmentDeleteModal.test.js
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Assessment/style.sass
  app/javascript/Application/components/common/PageModal.js
  app/javascript/Application/components/common/style.sass
  app/javascript/Application/styles/global/modal-styles.sass
Labels: patch

#472 CANS-972: Update Change Log after Delete Assessment
  app/controllers/api/assessments_controller.rb
  app/javascript/Application/App.api.js
  app/javascript/Application/App.api.test.js
  app/javascript/Application/components/Assessment/Assessment.service.js
  app/javascript/Application/components/Assessment/Assessment.service.test.js
  app/javascript/Application/components/Assessment/AssessmentDeleteModal.js
  app/javascript/Application/components/Assessment/AssessmentDeleteModal.test.js
  app/javascript/Application/components/Assessment/ChangeLog/AssessmentChangeLog.js
  app/javascript/Application/components/Assessment/ChangeLog/ChangeLogComment.js
  app/javascript/Application/components/Assessment/ChangeLog/ChangeLogComment.test.js
  docker-compose.ci.yml
  docker-compose.yml
  lib/assessments/assessments_repository.rb
  lib/infrastructure/http_service.rb
  spec/controllers/api/assessments_controller_spec.rb
  spec/lib/assessments/assessments_repository_spec.rb
  spec/page_objects/assessment_changelog.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: minor

#462 CANS-967. Assessment Date cannot be before the client's DOB
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader.test.js
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Assessment/AssessmentHelper.test.js
  app/javascript/Application/components/common/DateField.js
  app/javascript/Application/components/common/DateField.test.js
  app/javascript/Application/components/common/style.sass
  spec/page_objects/assessment_form.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: patch

#482 Patch: Fix misspell from original design of delete warning
  app/javascript/Application/components/Assessment/AssessmentDeleteModal.test.js
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/styles/global/modal-styles.sass
Labels: patch

#481 CANS-995: test hotfix with change to readme.md in protected hotfix branch
  README.md
Labels: patch

#483 CANS-995: ability to release hotfixes only from predefined protected hotfix branch
  Jenkinsfile
  Jenkinsfile_staging_regression.groovy
  README.md
Labels: patch

#484 CANS-972: bug fix
  app/javascript/Application/components/Assessment/ChangeLog/AssessmentChangeLog.js
Labels: bug, patch

#474 CANS-946 - Refactor a couple pages to isolate Layout components
  app/javascript/Application/components/Client/Client.js
  app/javascript/Application/components/Layout/BreadCrumb/BreadCrumbsBuilder.js
  app/javascript/Application/components/Layout/BreadCrumb/BreadCrumbsBuilder.test.js
  app/javascript/Application/components/Layout/ReactWoodDuckLayout.js
  app/javascript/Application/components/Layout/ReactWoodDuckLayout.test.js
  app/javascript/Application/components/Staff/CaseLoad/SubordinateInfoCard/StaffLoadingBoundary.test.js
  app/javascript/Application/components/pages/ChildListPage.js
  app/javascript/Application/components/pages/ChildListPage.test.js
  app/javascript/Application/components/pages/ChildProfilePage.js
  app/javascript/Application/components/pages/ChildProfilePage.test.js
  app/javascript/Application/components/pages/ChildProfilePageWithClient.js
  app/javascript/Application/components/pages/ChildProfilePageWithClient.test.js
  app/javascript/Application/components/pages/ClientLoadingBoundary.js
  app/javascript/Application/components/pages/ClientLoadingBoundary.test.js
  app/javascript/Application/components/pages/CurrentUserLoadingBoundary.js
  app/javascript/Application/components/pages/CurrentUserLoadingBoundary.test.js
  app/javascript/Application/components/pages/DashboardRedirectPage.js
  app/javascript/Application/components/pages/DashboardRedirectPage.test.js
  app/javascript/Application/components/pages/VisitLogger.js
  app/javascript/Application/components/pages/VisitLogger.test.js
  app/javascript/Application/components/pages/index.js
  app/javascript/Application/routes/Routes.js
  app/javascript/Application/routes/Routes.test.js
Labels: minor

#476 Fix for yarn dev to make CANS listen on PORT 3000
  Procfile.dev
  README.md
Labels: patch

#486 Assessment Date can be on the client's DOB
  app/javascript/Application/components/Assessment/AssessmentFormHeader.js
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Assessment/AssessmentHelper.test.js
  spec/regression/case_worker_scenarios_spec.rb
Labels: patch

#487 Upgrade react-widgets dependency version
  package.json
  spec/a11y/a11y_spec.rb
  yarn.lock
Labels: patch

#485 CANS-665 Domain or Item scroll up when it is expanded
  app/javascript/Application/components/Assessment/Domain.js
  app/javascript/Application/components/Assessment/Domain.test.js
  app/javascript/Application/components/Assessment/Item/Item.js
  app/javascript/Application/components/Assessment/Item/Item.test.js
  app/javascript/Application/util/assessmentAutoScroll.js
  app/javascript/Application/util/assessmentAutoScroll.test.js
  spec/page_objects/assessment_form.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: minor

#488 CANS-960 Behavioral/Emotional rating of “1” and “2” appear in summary AR column
  app/javascript/Application/components/Assessment/AssessmentSummary/ActionRequiredSummary.js
  app/javascript/Application/components/Assessment/AssessmentSummary/ActionRequiredSummary.test.js
  app/javascript/Application/components/Assessment/AssessmentSummary/DomainHelper.js
  app/javascript/Application/components/Assessment/AssessmentSummary/DomainHelper.test.js
  spec/regression/case_worker_scenarios_spec.rb
Labels: patch

#470 Code 140 Refactor Assessment Container
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/AssessmentContainerInner.js
  app/javascript/Application/components/Assessment/AssessmentContainerInner.test.js
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Assessment/AssessmentSummary/AssessmentSummaryCard.js
  app/javascript/Application/components/Assessment/WarningShow.js
  app/javascript/Application/components/Assessment/WarningShow.test.js
  app/javascript/Application/components/common/RenderWarning.js
  app/javascript/Application/components/common/RenderWarning.test.js
  app/javascript/Application/util/TimeoutService.js
Labels: patch

#490 CANS-946 - Add initial component library layout (flagged off by default)
  app/javascript/Application/components/Header/Header.js
  app/javascript/Application/components/Header/UserMenu.js
  app/javascript/Application/components/Header/UserMenu.test.js
  app/javascript/Application/components/Layout/DesignSystemLayout.js
  app/javascript/Application/components/Layout/DesignSystemLayout.test.js
  app/javascript/Application/components/Layout/FullWidthLayout.js
  app/javascript/Application/components/Layout/FullWidthLayout.test.js
  app/javascript/Application/components/Layout/rwd_overrides.sass
  app/javascript/Application/components/pages/ChildListPage.js
  app/javascript/Application/components/pages/ChildListPage.test.js
  app/javascript/Application/components/pages/ChildProfilePage.js
  app/javascript/Application/components/pages/ChildProfilePage.test.js
  app/javascript/Application/components/pages/ClientLoadingBoundary.js
  app/javascript/Application/components/pages/ClientLoadingBoundary.test.js
  app/javascript/Application/util/features.js
  app/javascript/Application/util/features.test.js
  app/javascript/Application/util/formatters.js
  app/javascript/Application/util/formatters.test.js
  config/feature.yml
Labels: minor

#492 Optimize and stabilize regression suite
  spec/acceptance_helper.rb
  spec/acceptance_helpers/login_helper.rb
  spec/page_objects/assessment_form.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: patch

#494 Fixing ProdLogin for RegressionSuite
  spec/acceptance_helpers/login_helper.rb
Labels: patch

#493 CANS-954-Adding more valid date formats for assesssment date
  app/javascript/Application/components/common/DateField.js
  app/javascript/Application/components/common/DateField.test.js
  app/javascript/Application/util/constants.js
Labels: minor

#497 Code 140
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/AssessmentContainerInner.js
  app/javascript/Application/components/Assessment/AssessmentContainerInner.test.js
Labels: patch

#498 Patch: Fix some issues about domain and item expanding auto scroll
  app/javascript/Application/components/Assessment/Domain.js
  app/javascript/Application/components/Assessment/DomainCommentAccordion.js
  app/javascript/Application/components/Assessment/DomainCommentAccordion.test.js
  app/javascript/Application/components/Assessment/Item/Item.js
  app/javascript/Application/util/assessmentAutoScroll.js
Labels: patch

#500 CANS-989 text on non-case carrying dashboard
  app/javascript/Application/components/Search/SearchContainer.js
  app/javascript/Application/components/Search/SearchContainer.test.js
Labels: patch

#501 CANS-982. Supervisor Dashboard: Info icon to clarify status columns
  app/javascript/Application/components/Assessment/AssessmentSummary/ActionRequiredSummary.js
  app/javascript/Application/components/Assessment/AssessmentSummary/ActionRequiredSummary.test.js
  app/javascript/Application/components/Assessment/AssessmentSummary/ImmediateActionRequiredSummary.js
  app/javascript/Application/components/Assessment/AssessmentSummary/ImmediateActionRequiredSummary.test.js
  app/javascript/Application/components/Assessment/AssessmentSummary/StrengthsSummary.js
  app/javascript/Application/components/Assessment/AssessmentSummary/StrengthsSummary.test.js
  app/javascript/Application/components/Assessment/AssessmentSummary/SummaryHeader.js
  app/javascript/Application/components/Assessment/AssessmentSummary/TraumaSummary.js
  app/javascript/Application/components/Assessment/AssessmentSummary/TraumaSummary.test.js
  app/javascript/Application/components/Assessment/Domain.js
  app/javascript/Application/components/Assessment/style.sass
  app/javascript/Application/components/Staff/StaffTable.js
  app/javascript/Application/components/Staff/StaffTable.test.js
  app/javascript/Application/components/common/DataGridHeader.js
  app/javascript/Application/components/common/DataGridHeader.test.js
  app/javascript/Application/components/common/style.sass
  app/javascript/Application/styles/global/global-styles.sass
  spec/page_objects/assessment_form.rb
Labels: patch

#502 CANS-986. Retain "number of rows" selected by user per session
  .gitignore
  app/javascript/Application/components/Assessment/ChangeLog/AssessmentChangeLog.js
  app/javascript/Application/components/Assessment/ChangeLog/AssessmentChangeLog.test.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryTable.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryTable.test.js
  app/javascript/Application/components/Client/ClientSocialWorkerCard.js
  app/javascript/Application/components/Client/ClientSocialWorkerCard.test.js
  app/javascript/Application/components/Staff/StaffTable.js
  app/javascript/Application/components/Staff/StaffTable.test.js
  app/javascript/Application/components/common/SessionDataGrid.js
  app/javascript/Application/components/common/SessionDataGrid.test.js
  app/javascript/Application/util/sessionStorageUtil.js
  app/javascript/Application/util/sessionStorageUtil.test.js
Labels: patch

#504 CANS-987: Changed Item-level chevron icon (left alignment) to make consistent w…
  app/javascript/Application/components/Assessment/style.sass
Labels: minor

#503 CANS-832 worker dashboard title
  app/javascript/Application/components/Client/ClientSocialWorkerCardTemplate.js
  app/javascript/Application/components/Client/ClientSocialWorkerCardTemplate.test.js
Labels: patch

#506 CANS-991. Fix typo
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConfidentialityAlert.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConfidentialityAlert.test.js
  spec/page_objects/assessment_form.rb
Labels: patch

#496 FIT-368 try 2 added smoke tests to release pipeline
  Jenkinsfile
  spec/regression/supervisor_login_spec.rb
Labels: patch

#505 CANS-945: age and date of birth on assessment page
  app/javascript/Application/components/Assessment/AssessmentFormHeader.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader.test.js
  app/javascript/Application/components/Assessment/assessment.mocks.test.js
  app/javascript/Application/util/dateHelper.js
  app/javascript/Application/util/dateHelper.test.js
  spec/page_objects/assessment_form.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: minor

#509 CANS-1031. Assessment header card styles cleaning
  app/javascript/Application/components/Assessment/AssessmentFormHeader.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader.test.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConductedByField.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConductedByField.test.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/UnderSixQuestion.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/style.sass
  app/javascript/Application/components/Assessment/DomainsHeader.js
  app/javascript/Application/components/Assessment/style.sass
  spec/page_objects/assessment_form.rb
Labels: patch

#512 CANS-945: styles adjusted to design
  app/javascript/Application/components/Assessment/AssessmentFormHeader.js
  app/javascript/Application/styles/global/typography.sass
Labels: patch

#510 CANS-946 - Use Component Library / Design System layout
  app/javascript/Application/components/Layout/DesignSystemLayout.js
  app/javascript/Application/components/Layout/DesignSystemLayout.test.js
  app/javascript/Application/components/Layout/FullWidthLayout.js
  app/javascript/Application/components/Layout/FullWidthLayout.test.js
  app/javascript/Application/components/Layout/ReactWoodDuckLayout.js
  app/javascript/Application/components/Layout/ReactWoodDuckLayout.test.js
  app/javascript/Application/util/assessmentAutoScroll.js
  app/javascript/Application/util/features.js
  app/javascript/Application/util/features.test.js
  config/feature.yml
  spec/acceptance_helpers/login_helper.rb
  spec/page_objects/assessment_form.rb
Labels: major

#513 Revert "CANS-946 - Use Component Library / Design System layout"
  app/javascript/Application/components/Layout/DesignSystemLayout.js
  app/javascript/Application/components/Layout/DesignSystemLayout.test.js
  app/javascript/Application/components/Layout/FullWidthLayout.js
  app/javascript/Application/components/Layout/FullWidthLayout.test.js
  app/javascript/Application/components/Layout/ReactWoodDuckLayout.js
  app/javascript/Application/components/Layout/ReactWoodDuckLayout.test.js
  app/javascript/Application/util/assessmentAutoScroll.js
  app/javascript/Application/util/features.js
  app/javascript/Application/util/features.test.js
  config/feature.yml
  spec/acceptance_helpers/login_helper.rb
  spec/page_objects/assessment_form.rb
Labels: patch

#514 Fix propType and warning modal errors
  app/javascript/Application/components/Assessment/AssessmentContainerInner.js
  app/javascript/Application/components/Assessment/WarningShow.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryRecord.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryTable.js
Labels: patch

#515 HOTFIX: CANS-1033, CANS-1034
  app/javascript/Application/components/Search/ClientSearch/QueryInput/InputField.js
  app/javascript/Application/components/Search/ClientSearch/QueryInput/InputField.test.js
  app/javascript/Application/components/Search/ClientSearch/QueryResults/PersonSuggestion/PersonSuggestion.js
  app/javascript/Application/components/Search/ClientSearch/QueryResults/PersonSuggestion/PersonSuggestion.test.js
Labels: patch

#517 CANS-1033, CANS-1034 to master
  app/javascript/Application/components/Search/ClientSearch/QueryInput/InputField.js
  app/javascript/Application/components/Search/ClientSearch/QueryInput/InputField.test.js
  app/javascript/Application/components/Search/ClientSearch/QueryResults/PersonSuggestion/PersonSuggestion.js
  app/javascript/Application/components/Search/ClientSearch/QueryResults/PersonSuggestion/PersonSuggestion.test.js
Labels: patch

#511 CANS-988 Caregiver Name field required with red text prompt
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Assessment/AssessmentHelper.test.js
  app/javascript/Application/components/Assessment/Domain.js
  app/javascript/Application/components/Assessment/Domain.test.js
  app/javascript/Application/components/Assessment/style.sass
  spec/regression/case_worker_scenarios_spec.rb
Labels: minor

#516 CANS-998: PreProd regression test pipeline added
  Jenkinsfile
  Jenkinsfile_staging_regression.groovy
Labels: patch

#520 CANS-1001 Confidential Check Marks will be Unchecked if the user selects "Yes" to Release of Info Question
  app/javascript/Application/components/Assessment/AssessmentFormHeader.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader.test.js
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Assessment/AssessmentHelper.test.js
  app/javascript/Application/components/Assessment/DomainItemList.test.js
  app/javascript/Application/components/Assessment/Item/ConfidentialCheckbox.js
  app/javascript/Application/components/Assessment/Item/ConfidentialCheckbox.test.js
  app/javascript/Application/components/Assessment/Item/Item.js
  app/javascript/Application/components/Assessment/Item/Item.test.js
  spec/regression/case_worker_scenarios_spec.rb
Labels: minor

#518 CANS-1013: When user clicks "print" modal appears to allow user to save their data before the action occurs
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Header/PageHeaderButtons/PrintButton.js
  app/javascript/Application/components/Header/PageHeaderButtons/PrintButton.test.js
  app/javascript/Application/components/common/UnsavedDataWarning.js
  app/javascript/Application/components/common/UnsavedDataWarning.test.js
  app/javascript/Application/styles/global/modal-styles.sass
  app/javascript/Application/util/constants.js
  spec/page_objects/assessment_form.rb
  spec/page_objects/sections/app_globals.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: minor

#521 FIT-393 Added the build discarder to the Jenkins file
  Jenkinsfile
Labels: patch

#523 CANS-953: AKA shown in search results if matching to search term
  app/javascript/Application/components/Search/ClientSearch/ClientFetcher.js
  app/javascript/Application/components/Search/ClientSearch/ClientFetcher.test.js
  app/javascript/Application/components/Search/ClientSearch/QueryResults/PersonSuggestion/AkaInfo.js
  app/javascript/Application/components/Search/ClientSearch/QueryResults/PersonSuggestion/AkaInfo.test.js
  app/javascript/Application/components/Search/ClientSearch/QueryResults/PersonSuggestion/PersonSuggestion.js
  app/javascript/Application/components/Search/ClientSearch/QueryResults/PersonSuggestion/PersonSuggestion.test.js
  app/javascript/Application/components/Search/ClientSearch/QueryResults/style.sass
  app/javascript/Application/components/Search/SearchHelper.js
  app/javascript/Application/components/Search/SearchHelper.test.js
  app/javascript/Application/components/Search/clientresults.mocks.js
  app/javascript/Application/components/Search/search.mocks.js
  app/javascript/Application/components/Search/selectors/SearchSelectors.js
  app/javascript/Application/components/Search/selectors/SearchSelectors.test.js
  legal/licenses.csv
  package.json
  yarn.lock
Labels: minor

#522 CANS-876-Collapse all domains when different age is selected
  app/javascript/Application/components/Assessment/Assessment.js
  app/javascript/Application/components/Assessment/Assessment.test.js
  app/javascript/Application/components/Assessment/AssessmentContainerInner.js
  app/javascript/Application/components/Assessment/AssessmentContainerInner.test.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader.test.js
Labels: minor

#526 CANS-834-Information icon next to Reassessment Reminder Date
  app/javascript/Application/components/Client/ClientSocialWorkerCardTemplate.js
  app/javascript/Application/components/Client/ClientSocialWorkerCardTemplate.test.js
Labels: minor

#525 CANS-946 - Use Component Library / Design System layout
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/style.sass
  app/javascript/Application/components/Layout/DesignSystemLayout.js
  app/javascript/Application/components/Layout/DesignSystemLayout.test.js
  app/javascript/Application/components/Layout/FullWidthLayout.js
  app/javascript/Application/components/Layout/FullWidthLayout.test.js
  app/javascript/Application/components/Layout/ReactWoodDuckLayout.js
  app/javascript/Application/components/Layout/ReactWoodDuckLayout.test.js
  app/javascript/Application/components/Layout/rwd_overrides.sass
  app/javascript/Application/util/assessmentAutoScroll.js
  app/javascript/Application/util/features.js
  app/javascript/Application/util/features.test.js
  config/feature.yml
  spec/acceptance_helpers/login_helper.rb
  spec/page_objects/assessment_form.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: minor

#524 CANS-755 Refactoring item component
  app/javascript/Application/components/Assessment/AssessmentFormHeader.js
  app/javascript/Application/components/Assessment/Item/Item.js
  app/javascript/Application/components/Assessment/Item/Item.test.js
  app/javascript/Application/components/Assessment/Item/ItemDescription.js
  app/javascript/Application/components/Assessment/Item/ItemDescription.test.js
  app/javascript/Application/components/Assessment/Item/ItemDescriptionRating.js
  app/javascript/Application/components/Assessment/Item/ItemHeader.js
  app/javascript/Application/components/Assessment/Item/ItemHeader.test.js
  app/javascript/Application/components/Assessment/Item/ItemHelper.js
  app/javascript/Application/components/Assessment/Item/ItemHelper.test.js
  app/javascript/Application/components/Assessment/Item/ItemInner.js
  app/javascript/Application/components/Assessment/Item/ItemInner.test.js
  app/javascript/Application/components/Assessment/Item/ItemNaCheckbox.js
  app/javascript/Application/components/Assessment/Item/ItemQtcDescriptions.js
  app/javascript/Application/components/Assessment/Item/ItemQtcDescriptions.test.js
  app/javascript/Application/components/Assessment/Item/ItemRating.js
  app/javascript/Application/components/Assessment/Item/ItemToolbarControls.js
  app/javascript/Application/components/Assessment/Item/ItemToolbarControls.test.js
Labels: minor

#527 CANS-1013: bug fix
  app/javascript/Application/components/Header/PageHeaderButtons/PrintButton.js
  app/javascript/Application/components/common/UnsavedDataWarning.js
  app/javascript/Application/util/eventBus.js
  app/javascript/Application/util/eventBus.test.js
Labels: bug, minor

#531 CANS-946 - Update CL to 0.8.4 for breadcrumb fix
  legal/licenses.csv
  package.json
  yarn.lock
Labels: patch

#529 CANS-990 Add chevron icons at bottom of every item and overall domain
  app/javascript/Application/components/Assessment/BottomCollapseIcon.js
  app/javascript/Application/components/Assessment/BottomCollapseIcon.test.js
  app/javascript/Application/components/Assessment/Domain.js
  app/javascript/Application/components/Assessment/Domain.test.js
  app/javascript/Application/components/Assessment/DomainCommentAccordion.js
  app/javascript/Application/components/Assessment/DomainCommentAccordion.test.js
  app/javascript/Application/components/Assessment/Item/Item.js
  app/javascript/Application/components/Assessment/Item/ItemDescription.js
  app/javascript/Application/components/Assessment/Item/ItemDescription.test.js
  app/javascript/Application/components/Assessment/Item/ItemInner.js
  app/javascript/Application/components/Assessment/Item/ItemInner.test.js
  app/javascript/Application/components/Assessment/Item/style.sass
  app/javascript/Application/components/Assessment/style.sass
  spec/page_objects/assessment_form.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: minor

#533 Removed period from tooltip
  app/javascript/Application/components/Client/ClientSocialWorkerCardTemplate.js
  app/javascript/Application/components/Client/ClientSocialWorkerCardTemplate.test.js
Labels: patch

#534 Change log print bug fix
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Header/PageHeaderButtons/PrintButton.js
  app/javascript/Application/components/Header/PageHeaderButtons/PrintButton.test.js
Labels: patch

#530 CANS-949 User can access the change log from assessment form
  app/javascript/Application/components/Assessment/AssessmentChangelogLink.js
  app/javascript/Application/components/Assessment/AssessmentChangelogLink.test.js
  app/javascript/Application/components/Assessment/AssessmentFormFooter.js
  app/javascript/Application/components/Assessment/AssessmentFormFooter.test.js
  app/javascript/Application/components/Assessment/style.sass
  app/javascript/Application/util/constants.js
  spec/page_objects/assessment_form.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: minor

#537 Cans 1032 docker compose
  README.md
  docker-compose.ci.yml
  docker-compose.yml
Labels: patch

#538 See if autoscroll hack fixes regression flakiness
  spec/regression/case_worker_scenarios_spec.rb
Labels: patch

#540 Wait for enabled field before interacting with it
  spec/page_objects/assessment_form.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: patch

#541 CANS-946 - IE/Windows bug fixes
  app/javascript/Application/components/Assessment/Item/ItemStyling.js
  app/javascript/Application/components/Assessment/style.sass
Labels: patch

#543 CANS-1015 - Log a NewRelic PageAction for Assessment Delete
  app/javascript/Application/components/Assessment/AssessmentActionsEllipsis.js
  app/javascript/Application/components/Assessment/AssessmentActionsEllipsis.test.js
  app/javascript/Application/components/Assessment/AssessmentDeleteModal.js
  app/javascript/Application/components/Assessment/AssessmentDeleteModal.test.js
  app/javascript/Application/components/Assessment/AssessmentRecordInfo.js
  app/javascript/Application/components/Assessment/AssessmentRecordInfo.test.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryTable.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryTable.test.js
Labels: patch

#544 CANS-1015 - Update NewRelic readme
  resources/docs/newrelic/readme.md
Labels: patch

#542 CANS-1057 Assessment Comment Icons
  app/javascript/Application/components/Assessment/DomainCommentAccordion.js
  app/javascript/Application/components/Assessment/DomainCommentAccordion.test.js
  app/javascript/Application/components/Assessment/DomainCommentIcon.js
  app/javascript/Application/components/Assessment/DomainCommentIcon.test.js
  app/javascript/Application/components/Assessment/Item/Item.test.js
  app/javascript/Application/components/Assessment/Item/ItemToolbarControls.js
  app/javascript/Application/components/Assessment/Item/ItemToolbarControls.test.js
  app/javascript/Application/components/common/Comment.js
  app/javascript/Application/components/common/Comment.test.js
  app/javascript/Application/components/common/CommentIcon.js
  app/javascript/Application/components/common/CommentIcon.test.js
  spec/regression/case_worker_scenarios_spec.rb
Labels: patch

#545 CANS-949 Show Change Log Link for Client from another county
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainerInner.js
  app/javascript/Application/components/Assessment/AssessmentContainerInner.test.js
  app/javascript/Application/components/Assessment/AssessmentFormFooter.js
  app/javascript/Application/components/Assessment/AssessmentFormFooter.test.js
  app/javascript/Application/components/Assessment/style.sass
  app/javascript/Application/components/common/UnsavedDataWarning.js
  app/javascript/Application/components/common/UnsavedDataWarning.test.js
Labels: patch

#546 Try clearing input field before setting
  spec/page_objects/assessment_form.rb
Labels: patch

#549 Update Component Library, for IE pagination fix
  legal/licenses.csv
  package.json
  yarn.lock
Labels: patch

#548 CANS-1017: Staff Id in Perry JSON is required to work with CANS
  lib/infrastructure/cwds_permission_checker.rb
  lib/infrastructure/security_policy.rb
  package.json
  spec/acceptance_helper.rb
  spec/acceptance_helpers/prod_login_helper.rb
  spec/lib/infrastructure/cwds_permission_checker_spec.rb
  spec/lib/infrastructure/security_policy_spec.rb
Labels: patch

#553 Fix failing because of February unit test
  app/javascript/Application/components/Client/ClientSocialWorkerCardTemplateHelper.test.js
Labels: patch

#547 CANS-1053 Print disabled until age template is selected
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Assessment/AssessmentHelper.test.js
  spec/page_objects/assessment_form.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: minor

#552 CANS-1070: Use React "History" approach for unsaved assessment warning
  app/javascript/Application/App.js
  app/javascript/Application/components/Assessment/AssessmentChangelogLink.js
  app/javascript/Application/components/Assessment/AssessmentChangelogLink.test.js
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Header/PageHeaderButtons/PrintButton.js
  app/javascript/Application/components/Layout/BreadCrumb/BreadCrumb.js
  app/javascript/Application/components/Layout/BreadCrumb/BreadCrumb.test.js
  app/javascript/Application/components/common/ExternalLink.js
  app/javascript/Application/components/common/ExternalLink.test.js
  app/javascript/Application/components/common/PageLockService.js
  app/javascript/Application/components/common/PageLockService.test.js
  app/javascript/Application/components/common/UnsavedDataWarning.js
  app/javascript/Application/components/common/UnsavedDataWarning.test.js
  app/javascript/Application/util/TimeoutService.js
  app/javascript/Application/util/TimeoutService.test.js
  app/javascript/Application/util/common.js
  app/javascript/Application/util/constants.js
  app/javascript/setupTests.js
Labels: minor
