Repository ca-cwds/cans, pull requests merged in 2019-04, with the labels that each got.

#613 CANS-1097: show summary on Print for saved assessments with all fields filled
  app/javascript/Application/components/Assessment/assessment.mocks.test.js
  app/javascript/Application/components/Print/PrintAssessment.js
  app/javascript/Application/components/Print/PrintAssessment.test.js
Labels: patch

#618 Refactoring for reassessment form preparation
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Assessment/AssessmentHelper.test.js
  app/javascript/Application/components/Client/ClientSocialWorkerCardTemplateHelper.test.js
Labels: patch, refactoring

#619 CANS-1080. Visual Indicator of Carried Over Ratings. Bug fix
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Assessment/AssessmentHelper.test.js
  app/javascript/Application/components/Assessment/DomainItemList.js
  app/javascript/Application/components/Assessment/DomainItemList.test.js
Labels: bug, patch

#617 CANS-1129: show summary after reload
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  spec/regression/case_worker_scenarios_spec.rb
Labels: patch

#620 CANS-1048 - Assessment option radio groups
  app/javascript/Application/components/Assessment/AssessmentFormHeader.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader.test.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/AssessmentOptions.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/AssessmentOptions.test.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/BooleanRadioGroup.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/BooleanRadioGroup.test.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/CanReleaseInfoQuestion.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/CanReleaseInfoQuestion.test.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConductedByField.test.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConfidentialityAlert.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConfidentialityAlert.test.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/HasCaregiverQuestion.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/HasCaregiverQuestion.test.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/RadioGroupMessageBox.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/RadioGroupMessageBox.test.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/style.sass
  app/javascript/Application/components/Assessment/style.sass
  spec/page_objects/assessment_form.rb
Labels: minor

#622 CANS-1124. The reassessment accounts for item number changes
  app/javascript/Application/components/Assessment/Assessment.js
  app/javascript/Application/components/Assessment/Assessment.test.js
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/AssessmentContainerInner.js
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Assessment/AssessmentHelper.test.js
  app/javascript/Application/components/Assessment/DomainItemList.js
  app/javascript/Application/components/Assessment/FormFooter/AssessmentFormFooter.js
  app/javascript/Application/components/Assessment/FormFooter/AssessmentFormFooter.test.js
  app/javascript/Application/components/Assessment/ReassessmentHelper.js
  app/javascript/Application/components/Assessment/ReassessmentHelper.test.js
  app/javascript/Application/components/Assessment/assessment.mocks.test.js
  app/javascript/Application/components/Assessment/index.js
Labels: minor

#621 CANS-1113: timeout warning refactored to use cwds/components
  app/javascript/Application/components/common/TimeoutWarning.js
  app/javascript/Application/components/common/TimeoutWarning.test.js
Labels: patch

#623 (Preint acceptance test stabilization?) Set review checkbox directly
  app/javascript/Application/components/Assessment/FormFooter/ReviewConfirmation.js
  spec/page_objects/assessment_form.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: patch

#625 CANS-1116: confidential items hidden from Assessment Summary on Print
  app/javascript/Application/components/Print/PrintAssessment.js
  app/javascript/Application/components/Print/PrintSummary.js
  app/javascript/Application/components/Print/PrintSummary.test.js
  app/javascript/Application/components/Print/PrintSummaryRecord.js
  app/javascript/Application/components/Print/PrintSummaryRecord.test.js
Labels: patch

#626 Stabilize reassessment check
  spec/helpers/assessment_helper.rb
  spec/page_objects/assessment_form.rb
Labels: patch

#627 Update bootstrap and rails for security patches
  Gemfile
  Gemfile.lock
  app/javascript/Application/components/Client/AssessmentComparison/comparisonTable/ComparisonOuterTableExpander.js
  package.json
  yarn.lock
Labels: patch

#628 CANS-1069 Capture Comment on Printed CANS Assessment Change Log
  app/javascript/Application/components/Assessment/ChangeLog/PrintChangeLog.js
  app/javascript/Application/components/Assessment/ChangeLog/PrintChangeLog.test.js
  app/javascript/Application/components/Assessment/ChangeLog/PrintChangeLogTable.js
  app/javascript/Application/components/Assessment/ChangeLog/PrintChangeLogTable.test.js
Labels: minor

#631 CANS-1048 (bug-fix) - Add color to selected radio options
  app/javascript/Application/components/Assessment/AssessmentFormHeader/BooleanRadioGroup.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/BooleanRadioGroup.test.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/style.sass
Labels: patch

#632 CANS-1069 Add assessment date to print
  app/javascript/Application/components/Assessment/ChangeLog/PrintChangeLog.js
  app/javascript/Application/components/Assessment/ChangeLog/PrintChangeLog.test.js
Labels: patch

#630 CANS-1137 Do not carry over N/A checked boxes in Reassessment
  app/javascript/Application/components/Assessment/Item/ItemNaCheckbox.js
  app/javascript/Application/components/Assessment/Item/ItemNaCheckbox.test.js
  app/javascript/Application/components/Assessment/Item/ItemRating.js
  app/javascript/Application/components/Assessment/Item/ItemRating.test.js
  app/javascript/Application/components/Assessment/Item/ItemToolbarControls.js
  app/javascript/Application/components/Assessment/Item/ItemToolbarControls.test.js
  app/javascript/Application/components/Assessment/Item/style.sass
  app/javascript/Application/components/Assessment/ReassessmentHelper.js
  app/javascript/Application/components/Assessment/ReassessmentHelper.test.js
Labels: minor

#635 [CANS-1048] Add asterisks to boolean group legends
  app/javascript/Application/components/Assessment/AssessmentFormHeader/CanReleaseInfoQuestion.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/CanReleaseInfoQuestion.test.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/HasCaregiverQuestion.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/HasCaregiverQuestion.test.js
Labels: patch

#636 CANS-1039 Update Styles and Fonts on Compare Overtime Page
  app/javascript/Application/components/Client/AssessmentComparison/comparisonGraph/ComparisonGraph.js
  app/javascript/Application/components/Client/AssessmentComparison/comparisonGraph/ComparisonGraphInner.js
  app/javascript/Application/components/Client/AssessmentComparison/comparisonGraph/comparisonGraphDataTransformations.js
  app/javascript/Application/components/Client/AssessmentComparison/comparisonTable/ComparisonInnerTable.js
  app/javascript/Application/components/Client/AssessmentComparison/comparisonTable/ComparisonOuterTable.js
  app/javascript/Application/components/Client/AssessmentComparison/style.sass
  app/javascript/Application/components/Client/Client.helper.js
  app/javascript/Application/components/Client/Client.helper.test.js
  app/javascript/Application/components/Client/ClientAssessmentStatisticsHeader.test.js
  app/javascript/Application/components/common/AgeRangeSwitch.js
  app/javascript/Application/components/common/style.sass
Labels: minor

#634 CANS-837. Supervisor Dashboard: Add "Reassessments Needed" column
  app/javascript/Application/components/Staff/ReassessmentsDueCalculator.js
  app/javascript/Application/components/Staff/ReassessmentsDueCalculator.test.js
  app/javascript/Application/components/Staff/ReassessmentsNeededCell.js
  app/javascript/Application/components/Staff/ReassessmentsNeededCell.test.js
  app/javascript/Application/components/Staff/ReassessmentsNeededCellBadge.js
  app/javascript/Application/components/Staff/ReassessmentsNeededCellBadge.test.js
  app/javascript/Application/components/Staff/StaffTable.js
  app/javascript/Application/components/Staff/StaffTable.test.js
  app/javascript/Application/components/Staff/style.sass
  app/javascript/Application/components/common/DataGridHeader.js
Labels: minor

#624 CANS-831 Add component for Reminder Date Pill
  app/javascript/Application/components/Client/ClientSocialWorkerCardTemplate.js
  app/javascript/Application/components/Client/ClientSocialWorkerCardTemplate.test.js
  app/javascript/Application/components/Client/ClientSocialWorkerCardTemplateHelper.js
  app/javascript/Application/components/Client/ClientSocialWorkerCardTemplateHelper.test.js
  app/javascript/Application/components/Client/ReminderDateCell.js
  app/javascript/Application/components/Client/ReminderDateCell.test.js
  app/javascript/Application/components/Staff/ReassessmentsDueCalculator.js
Labels: patch

#639 CANS-1104: Ability to Edit in "Complete" Status 7 Days After Clicking Complete
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader.test.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/style.sass
  app/javascript/Application/components/Assessment/ChangeLog/StatusChangeTypes.js
  app/javascript/Application/components/Assessment/CompleteModal.js
  app/javascript/Application/components/Assessment/CompleteModal.test.js
  app/javascript/Application/components/Assessment/FormFooter/AssessmentFormFooter.js
  app/javascript/Application/components/Assessment/FormFooter/AssessmentFormFooter.test.js
  app/javascript/Application/components/Assessment/FormFooter/FooterControls.js
  app/javascript/Application/components/Assessment/FormFooter/FooterControls.test.js
  docker-compose.ci.yml
  docker-compose.yml
  spec/page_objects/assessment_form.rb
  spec/page_objects/sections/app_globals.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: minor

#637 CANS-1135, CANS-1002: update to cwds/components:1.3.0. Buttons update
  app/javascript/Application/components/Assessment/AssessmentActionsEllipsis.js
  app/javascript/Application/components/Assessment/ChangelogLink.js
  app/javascript/Application/components/Assessment/ChangelogLink.test.js
  app/javascript/Application/components/Assessment/CompleteModal.js
  app/javascript/Application/components/Assessment/Domain.js
  app/javascript/Application/components/Assessment/Domain.test.js
  app/javascript/Application/components/Assessment/DomainCaregiverControls.js
  app/javascript/Application/components/Assessment/DomainCaregiverControls.test.js
  app/javascript/Application/components/Assessment/DomainCollapseButton.js
  app/javascript/Application/components/Assessment/DomainCollapseButton.test.js
  app/javascript/Application/components/Assessment/DomainsHeader.js
  app/javascript/Application/components/Assessment/FormFooter/CancelAssessmentButton.js
  app/javascript/Application/components/Assessment/FormFooter/CompleteAssessmentButton.js
  app/javascript/Application/components/Assessment/FormFooter/CompleteAssessmentButton.test.js
  app/javascript/Application/components/Assessment/ReassessmentModal.js
  app/javascript/Application/components/Assessment/ReassessmentModal.test.js
  app/javascript/Application/components/Assessment/style.sass
  app/javascript/Application/components/Client/AddCansButton.js
  app/javascript/Application/components/Client/style.sass
  app/javascript/Application/components/Header/PageHeaderButtonsBuilder.js
  app/javascript/Application/components/Header/PageHeaderButtonsBuilder.test.js
  app/javascript/Application/components/Header/UserMenu.js
  app/javascript/Application/components/Header/style.sass
  app/javascript/Application/components/Search/ClientSearch/QueryResults/ShowMoreResultsButton.js
  app/javascript/Application/components/common/AgeRangeSwitch.js
  app/javascript/Application/components/common/TimeoutWarning.js
  app/javascript/Application/components/common/UnsavedDataWarning.js
  app/javascript/Application/components/common/style.sass
  app/javascript/Application/styles/global/colors.sass
  app/javascript/Application/styles/global/cwds-conflict-fixes.sass
  app/javascript/Application/styles/global/modal-styles.sass
  legal/licenses.csv
  package.json
  spec/page_objects/assessment_form.rb
  yarn.lock
Labels: minor

#643 CANS-1136: Refactor Delete Modal to Incorporate Component Library
  app/javascript/Application/components/Assessment/AssessmentDeleteModal.js
  app/javascript/Application/components/Assessment/AssessmentDeleteModal.test.js
  spec/page_objects/sections/app_globals.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: minor

#638 CANS-1065. Improve Retain "number of rows" selected by user per session
  app/javascript/Application/components/Header/UserMenu.js
  app/javascript/Application/components/Header/UserMenu.test.js
  app/javascript/Application/components/common/PageLockService.js
  app/javascript/Application/components/common/PageLockService.test.js
  app/javascript/Application/components/common/TimeoutWarning.js
  app/javascript/Application/components/common/TimeoutWarning.test.js
  app/javascript/Application/components/common/UserAccountService.js
  app/javascript/Application/components/common/UserAccountService.test.js
  app/javascript/Application/util/navigationUtil.js
  app/javascript/Application/util/navigationUtil.test.js
  app/javascript/Application/util/sessionStorageUtil.js
  app/javascript/Application/util/sessionStorageUtil.test.js
  spec/acceptance_helpers/login_helper.rb
Labels: patch

#640 CANS-1107 2.0 Print Functionality Implemented
  app/javascript/Application/components/Assessment/assessment.mocks.test.js
  app/javascript/Application/components/Print/Print.js
  app/javascript/Application/components/Print/Print.test.js
  app/javascript/Application/components/Print/PrintAssessment.js
  app/javascript/Application/components/Print/PrintAssessment.test.js
  app/javascript/Application/components/Print/PrintAssessmentStyle.js
  app/javascript/Application/components/Print/PrintHelper.js
  app/javascript/Application/components/Print/PrintSummaryRecord.js
  app/javascript/Application/components/Print/index.js
  app/javascript/Application/components/Print/printAssessment/PrintAssessment.js
  app/javascript/Application/components/Print/printAssessment/PrintAssessment.test.js
  app/javascript/Application/components/Print/printAssessment/PrintAssessmentHeader.js
  app/javascript/Application/components/Print/printAssessment/PrintAssessmentHeader.test.js
  app/javascript/Application/components/Print/printAssessment/PrintAssessmentHeaderOptions.js
  app/javascript/Application/components/Print/printAssessment/PrintAssessmentHeaderOptions.test.js
  app/javascript/Application/components/Print/printAssessment/PrintAssessmentHeadline.js
  app/javascript/Application/components/Print/printAssessment/PrintAssessmentHeadline.test.js
  app/javascript/Application/components/Print/printAssessment/PrintAssessmentHelper.js
  app/javascript/Application/components/Print/printAssessment/PrintAssessmentHelper.test.js
  app/javascript/Application/components/Print/printAssessment/PrintAssessmentOverallFooter.js
  app/javascript/Application/components/Print/printAssessment/PrintAssessmentOverallFooter.test.js
  app/javascript/Application/components/Print/printAssessment/PrintAssessmentOverallHeader.js
  app/javascript/Application/components/Print/printAssessment/PrintAssessmentOverallHeader.test.js
  app/javascript/Application/components/Print/printAssessment/PrintAssessmentStyle.js
  app/javascript/Application/components/Print/printAssessment/PrintDomain.js
  app/javascript/Application/components/Print/printAssessment/PrintDomain.test.js
  app/javascript/Application/components/Print/printAssessment/PrintDomainCommentHeader.js
  app/javascript/Application/components/Print/printAssessment/PrintDomainCommentHeader.test.js
  app/javascript/Application/components/Print/printAssessment/PrintDomainHeader.js
  app/javascript/Application/components/Print/printAssessment/PrintDomainHeader.test.js
  app/javascript/Application/components/Print/printAssessment/PrintItem.js
  app/javascript/Application/components/Print/printAssessment/PrintItem.test.js
  app/javascript/Application/components/Print/printAssessment/PrintOptions.js
  app/javascript/Application/components/Print/printAssessment/PrintOptions.test.js
  app/javascript/Application/components/Print/printAssessment/PrintSummary.js
  app/javascript/Application/components/Print/printAssessment/PrintSummary.test.js
  app/javascript/Application/components/Print/printAssessment/PrintSummaryRecord.js
  app/javascript/Application/components/Print/printAssessment/PrintSummaryRecord.test.js
  app/javascript/Application/components/Print/printUtil/CWDSlogo.js
  app/javascript/Application/components/Print/printUtil/CWDSlogo.test.js
  app/javascript/Application/components/Print/printUtil/CategoryHeader.js
  app/javascript/Application/components/Print/printUtil/CategoryHeader.test.js
  app/javascript/Application/components/Print/printUtil/CheckedRadio.js
  app/javascript/Application/components/Print/printUtil/CheckedRadio.test.js
  app/javascript/Application/components/Print/printUtil/HeaderSvgBg.js
  app/javascript/Application/components/Print/printUtil/HeaderSvgBg.test.js
  app/javascript/Application/components/Print/printUtil/PrintHelper.js
  app/javascript/Application/components/Print/printUtil/PrintHelper.test.js
  app/javascript/Application/components/Print/printUtil/PrintLayout.js
  app/javascript/Application/components/Print/printUtil/PrintLayout.test.js
  app/javascript/Application/components/Print/printUtil/PrintPageBreaker.js
  app/javascript/Application/components/Print/printUtil/PrintPageBreaker.test.js
  app/javascript/Application/components/Print/printUtil/UncheckedRadio.js
  app/javascript/Application/components/Print/printUtil/UncheckedRadio.test.js
Labels: minor

#641 CANS-831 sort reminder date and left justify the cell content
  app/javascript/Application/components/Client/ClientSocialWorkerCardTemplate.js
Labels: patch

#642 CANS-837. Break "Reassessments Needed" column on Supervisor dashboard
  app/javascript/Application/components/Client/ReminderDateCell.js
  app/javascript/Application/components/Staff/ReassessmentsDueCalculator.js
  app/javascript/Application/components/Staff/ReassessmentsDueCalculator.test.js
  app/javascript/Application/components/Staff/ReassessmentsNeededCell.js
  app/javascript/Application/components/Staff/ReassessmentsNeededCell.test.js
  app/javascript/Application/components/Staff/ReassessmentsNeededCellBadge.js
  app/javascript/Application/components/Staff/ReassessmentsNeededCellBadge.test.js
  app/javascript/Application/components/Staff/StaffTable.js
  app/javascript/Application/components/Staff/StaffTable.test.js
  app/javascript/Application/components/Staff/style.sass
  app/javascript/Application/util/dateHelper.js
Labels: patch

#645 CANS-1133 Refactor Navigation Warning Modal to Incorporate Component Library
  app/javascript/Application/components/Assessment/CompleteModal.js
  app/javascript/Application/components/common/UnsavedDataWarning.js
  app/javascript/Application/components/common/UnsavedDataWarning.test.js
  app/javascript/Application/styles/global/modal-styles.sass
  spec/page_objects/sections/app_globals.rb
Labels: minor

#647 CANS-1113: IE11 fix for timeout modal window
  app/javascript/Application/components/Client/ClientSocialWorkerCard.js
  app/javascript/Application/components/Client/ClientSocialWorkerCard.test.js
  app/javascript/Application/components/Staff/Supervisor/SubordinateCard.js
  app/javascript/Application/components/Staff/Supervisor/SubordinateCard.test.js
  app/javascript/Application/components/common/TimeoutWarning.js
Labels: patch

#644 CANS-1099-Assessment Form Header Case / Referral
  app/javascript/Application/components/Assessment/AssessmentFormHeader.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader.test.js
  app/javascript/Application/components/Assessment/style.sass
  app/javascript/Application/styles/global/typography.sass
Labels: minor

#648 CANS-831 refactor date sorting and add sort method to reminder date col
  app/javascript/Application/components/Client/ClientSocialWorkerCardTemplate.js
  app/javascript/Application/components/Client/ClientSocialWorkerCardTemplate.test.js
  app/javascript/Application/components/Client/ClientSocialWorkerCardTemplateHelper.js
  app/javascript/Application/components/Client/ClientSocialWorkerCardTemplateHelper.test.js
  app/javascript/Application/util/dateHelper.js
  app/javascript/Application/util/dateHelper.test.js
Labels: patch

#650 CANS-1133 Update navigation modal with new changes proposed by design team.
  app/javascript/Application/components/common/UnsavedDataWarning.js
  app/javascript/Application/components/common/UnsavedDataWarning.test.js
  spec/page_objects/sections/app_globals.rb
Labels: minor

#651 CANS-1101 Print Modal to Redacted or Not Redacted
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Assessment/AssessmentHelper.test.js
  app/javascript/Application/components/Assessment/AssessmentPrintModal.js
  app/javascript/Application/components/Assessment/AssessmentPrintModal.test.js
  app/javascript/Application/components/Assessment/assessment.mocks.test.js
  app/javascript/Application/components/Assessment/style.sass
  app/javascript/Application/components/Header/PageHeaderButtons/PrintButton.js
  app/javascript/Application/components/Header/PageHeaderButtons/PrintButton.test.js
  app/javascript/Application/components/Header/style.sass
  app/javascript/Application/components/Print/printAssessment/PrintAssessment.js
  app/javascript/Application/components/Print/printAssessment/PrintAssessment.test.js
  app/javascript/Application/components/Print/printAssessment/PrintAssessmentHelper.js
  app/javascript/Application/components/Print/printAssessment/PrintAssessmentHelper.test.js
  app/javascript/Application/components/Print/printAssessment/PrintDomain.js
  app/javascript/Application/components/Print/printAssessment/PrintDomain.test.js
  app/javascript/Application/components/Print/printAssessment/PrintItem.js
  app/javascript/Application/components/Print/printAssessment/PrintItem.test.js
Labels: minor

#652 Patch-New print bug fixing and improvement
  app/javascript/Application/components/Print/Print.js
  app/javascript/Application/components/Print/printAssessment/PrintAssessment.js
  app/javascript/Application/components/Print/printAssessment/PrintAssessment.test.js
  app/javascript/Application/components/Print/printAssessment/PrintAssessmentStyle.js
  app/javascript/Application/components/Print/printAssessment/PrintDomain.js
  app/javascript/Application/components/Print/printAssessment/PrintDomain.test.js
  app/javascript/Application/components/Print/printAssessment/PrintDomainCommentHeader.js
  app/javascript/Application/components/Print/printAssessment/PrintDomainCommentHeader.test.js
  app/javascript/Application/components/Print/printAssessment/PrintSummary.js
  app/javascript/Application/components/Print/printAssessment/PrintSummary.test.js
  app/javascript/Application/components/Print/printAssessment/PrintSummaryRecord.js
  app/javascript/Application/components/Print/printUtil/CategoryHeader.js
  app/javascript/Application/components/Print/printUtil/PrintHelper.js
  app/javascript/Application/components/Print/style.sass
Labels: patch

#656 CANS-1133 Revert navigation modal changes
  app/javascript/Application/components/common/UnsavedDataWarning.js
  app/javascript/Application/components/common/UnsavedDataWarning.test.js
  spec/page_objects/sections/app_globals.rb
Labels: patch

#657 CANS-1113: IE 11 fix for card overlapping modal
  app/javascript/Application/components/Client/ClientSocialWorkerCard.js
  app/javascript/Application/components/Print/printAssessment/PrintDomain.js
  app/javascript/Application/components/Staff/Supervisor/SubordinateCard.js
  app/javascript/Application/components/Staff/Supervisor/SubordinateCard.test.js
  app/javascript/Application/components/common/TimeoutWarning.js
  app/javascript/Application/components/common/TimeoutWarning.test.js
  app/javascript/Application/styles/global/card.sass
  spec/page_objects/assessment_form.rb
Labels: patch

#646 CANS-1079 - Expand All / Collapse All edge cases
  app/javascript/Application/components/Assessment/Assessment.js
  app/javascript/Application/components/Assessment/Assessment.test.js
  app/javascript/Application/components/Assessment/AssessmentCard.js
  app/javascript/Application/components/Assessment/AssessmentCard.test.js
  app/javascript/Application/components/Assessment/AssessmentContainerInner.js
  app/javascript/Application/components/Assessment/AssessmentContainerInner.test.js
  app/javascript/Application/components/Assessment/Domain.js
  app/javascript/Application/components/Assessment/Domain.test.js
  app/javascript/Application/components/Assessment/DomainComment.js
  app/javascript/Application/components/Assessment/DomainExpansionController.js
  app/javascript/Application/components/Assessment/DomainExpansionController.test.js
  app/javascript/Application/components/Assessment/DomainItemList.js
  app/javascript/Application/components/Assessment/DomainsHeader.js
  app/javascript/Application/components/Assessment/DomainsHeader.test.js
  app/javascript/Application/components/Assessment/Item/Item.js
  app/javascript/Application/components/Assessment/assessment.mocks.test.js
  spec/page_objects/assessment_form.rb
  spec/regression/case_worker_scenarios_spec.rb
  spec/regression/supervisor_login_spec.rb
Labels: minor

#661 CANS-1170 Delete CANS modal displays wrong assessment date fix
  app/javascript/Application/components/Assessment/AssessmentRecordInfo.js
  app/javascript/Application/components/Assessment/AssessmentRecordInfo.test.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryTable.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryTable.test.js
Labels: patch

#662 CANS-1144 Update Component Library
  package.json
  yarn.lock
Labels: patch

#664 CANS-1157 - Refactor Item
  app/javascript/Application/components/Assessment/Item/Item.js
  app/javascript/Application/components/Assessment/Item/Item.test.js
Labels: patch

#665 CANS-1165- Change delete reason text
  app/javascript/Application/components/Assessment/AssessmentDeleteModal.test.js
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Assessment/ChangeLog/PrintChangeLogTable.test.js
Labels: minor

#663 CANS-1163: Caregiver Delete Warning refactoring
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/AssessmentContainerInner.js
  app/javascript/Application/components/Assessment/AssessmentContainerInner.test.js
  app/javascript/Application/components/Assessment/AssessmentDeleteModal.test.js
  app/javascript/Application/components/Assessment/style.sass
  app/javascript/Application/components/common/CaregiverDeleteWarning.js
  app/javascript/Application/components/common/CaregiverDeleteWarning.test.js
  app/javascript/Application/components/common/PageModal.js
  app/javascript/Application/components/common/PageModal.test.js
  app/javascript/Application/components/common/RenderWarning.js
  app/javascript/Application/components/common/RenderWarning.test.js
  app/javascript/Application/components/common/index.js
  spec/acceptance_helper.rb
  spec/page_objects/assessment_form.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: patch

#667 Cans 1126 fix assessment history bug
  app/javascript/Application/components/Assessment/AssessmentContainerInner.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader.test.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryLoadingBoundary.test.js
  app/javascript/Application/components/Client/ClientAssessmentStatistics.js
  app/javascript/Application/components/Client/ClientAssessmentStatisticsHeader.js
  app/javascript/Application/components/Client/ClientAssessmentStatisticsHeader.test.js
Labels: patch

#660 CANS-1174 update complete conformation modal text
  app/javascript/Application/components/Assessment/CompleteModal.js
  app/javascript/Application/components/Assessment/CompleteModal.test.js
Labels: patch

#658 CANS-1130 Change ToolTips to InfoTips
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/AssessmentSummary/ActionRequiredSummary.js
  app/javascript/Application/components/Assessment/AssessmentSummary/ActionRequiredSummary.test.js
  app/javascript/Application/components/Assessment/AssessmentSummary/ImmediateActionRequiredSummary.js
  app/javascript/Application/components/Assessment/AssessmentSummary/ImmediateActionRequiredSummary.test.js
  app/javascript/Application/components/Assessment/AssessmentSummary/StrengthsSummary.js
  app/javascript/Application/components/Assessment/AssessmentSummary/StrengthsSummary.test.js
  app/javascript/Application/components/Assessment/AssessmentSummary/TraumaSummary.js
  app/javascript/Application/components/Assessment/AssessmentSummary/TraumaSummary.test.js
  app/javascript/Application/components/Assessment/Domain.js
  app/javascript/Application/components/Assessment/Domain.test.js
  app/javascript/Application/components/Client/ClientSocialWorkerCardTemplate.js
  app/javascript/Application/components/Staff/StaffTable.js
  app/javascript/Application/components/common/DataGridHeader.js
  app/javascript/Application/components/common/DataGridHeader.test.js
  package-lock.json
  package.json
  spec/page_objects/assessment_form.rb
  yarn.lock
Labels: minor

#669 CANS-1174 add line break to complete modal text
  app/javascript/Application/components/Assessment/CompleteModal.js
  app/javascript/Application/components/Assessment/CompleteModal.test.js
Labels: patch

#671 Removing package-lock file.
  package-lock.json
Labels: patch

#670 CANS-1176 Fix IE 11 Print Issues
  .gitignore
  app/javascript/Application/components/Print/Print.js
  app/javascript/Application/components/Print/Print.test.js
  app/javascript/Application/components/Print/printAssessment/PrintAssessmentStyle.js
  app/javascript/Application/components/Print/printAssessment/PrintSummary.js
  app/javascript/Application/components/Print/printUtil/PrintHelper.js
  app/javascript/Application/components/Print/printUtil/PrintHelper.test.js
  app/javascript/Application/components/Print/printUtil/PrintPageBreaker.js
  app/javascript/Application/components/Print/printUtil/PrintPageBreaker.test.js
  app/javascript/Application/components/Print/style.sass
Labels: minor

#672 CANS-1168 CANS Summary Card Text Wraps
  app/javascript/Application/components/Assessment/AssessmentSummary/SummaryGrid.test.js
  app/javascript/Application/components/Assessment/AssessmentSummary/style.sass
Labels: minor

#668 Upgrade webpack and dependencies
  .babelrc
  .browserslistrc
  Gemfile
  Gemfile.lock
  app/javascript/packs/application.js
  bin/webpack
  bin/webpack-dev-server
  config/webpacker.yml
  jest.config.js
  legal/licenses.csv
  package.json
  yarn.lock
Labels: minor

#666 CANS-1157 - Refactor caregiver indexing to avoid UNSAFE_componentWillReceiveProps
  app/javascript/Application/components/Assessment/Assessment.js
  app/javascript/Application/components/Assessment/Assessment.test.js
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/AssessmentMutations.js
  app/javascript/Application/components/Assessment/AssessmentMutations.test.js
Labels: minor

#675 Update Items for better React performance
  app/javascript/Application/components/Assessment/Assessment.js
  app/javascript/Application/components/Assessment/AssessmentMutations.js
  app/javascript/Application/components/Assessment/AssessmentMutations.test.js
  app/javascript/Application/components/Assessment/DomainItemList.js
  app/javascript/Application/components/Assessment/DomainItemList.test.js
  app/javascript/Application/components/Assessment/Item/Item.js
  app/javascript/Application/components/Assessment/Item/Item.test.js
Labels: patch

#673 CANS-1167: performance improvements
  app/javascript/Application/components/Assessment/Domain.js
  app/javascript/Application/components/Assessment/Domain.test.js
Labels: patch

#677 Use full i18n object in Domain to avoid unnecessary renders
  app/javascript/Application/components/Assessment/AssessmentCard.js
  app/javascript/Application/components/Assessment/Domain.js
  app/javascript/Application/components/Assessment/Domain.test.js
Labels: patch

#678 CANS-1168 Fix for IE issue with cans-summary items.
  app/javascript/Application/components/Assessment/AssessmentSummary/style.sass
Labels: patch

#679 Performance Refactors for Assessment page load and Expand/Collapse
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/Domain.js
  app/javascript/Application/components/Assessment/Domain.test.js
  app/javascript/Application/components/Assessment/DomainPanelSummary.js
  app/javascript/Application/components/Assessment/DomainPanelSummary.test.js
Labels: patch

#681 Cans 1178 fix production build issues
  app/javascript/Application/style.sass
  config/webpack/production.js
Labels: patch

#683 Patch isReviewed logic regression
  app/javascript/Application/components/Assessment/Domain.js
  app/javascript/Application/components/Assessment/Domain.test.js
  app/javascript/Application/components/Assessment/DomainPanelSummary.js
Labels: patch

#682 CANS-1175 Print caregiver domain and summary cards refactoring
  app/javascript/Application/components/Print/printAssessment/PrintAssessment.js
  app/javascript/Application/components/Print/printAssessment/PrintAssessment.test.js
  app/javascript/Application/components/Print/printAssessment/PrintAssessmentHeader.js
  app/javascript/Application/components/Print/printAssessment/PrintAssessmentHeader.test.js
  app/javascript/Application/components/Print/printAssessment/PrintAssessmentStyle.js
  app/javascript/Application/components/Print/printAssessment/PrintCaregiverName.js
  app/javascript/Application/components/Print/printAssessment/PrintCaregiverName.test.js
  app/javascript/Application/components/Print/printAssessment/PrintDomain.js
  app/javascript/Application/components/Print/printAssessment/PrintDomain.test.js
  app/javascript/Application/components/Print/printAssessment/PrintDomainCommentHeader.js
  app/javascript/Application/components/Print/printAssessment/PrintSummary.js
  app/javascript/Application/components/Print/printAssessment/PrintSummary.test.js
  app/javascript/Application/components/Print/printAssessment/PrintSummaryRecord.js
Labels: minor

#680 CANS-1030: Enhance the "Assessment Conducted By" field
  app/javascript/Application/components/Assessment/AssessmentFormHeader.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader.test.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConductedBy.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConductedBy.test.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConductedByField.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConductedByField.test.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConductedByNameField.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConductedByNameField.test.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConductedByRole.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConductedByRole.test.js
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Assessment/AssessmentHelper.test.js
  app/javascript/Application/components/Assessment/FormFooter/FooterControls.js
  app/javascript/Application/components/Assessment/FormFooter/FooterControls.test.js
  app/javascript/Application/components/Assessment/assessment.mocks.test.js
  app/javascript/Application/components/Assessment/style.sass
  app/javascript/Application/components/Print/printAssessment/PrintAssessment.js
  app/javascript/Application/components/Print/printAssessment/PrintAssessmentHeader.js
  app/javascript/Application/components/Print/printAssessment/PrintAssessmentHeader.test.js
  app/javascript/Application/components/Print/printAssessment/PrintAssessmentStyle.js
  app/javascript/Application/util/common.js
  app/javascript/Application/util/common.test.js
  docker-compose.ci.yml
  docker-compose.yml
  spec/a11y/a11y_spec.rb
  spec/page_objects/assessment_form.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: minor

#686 CANS-1030: test fix
  spec/page_objects/assessment_form.rb
Labels: minor

#684 CANS-1182 Use ToolTips for Domains on Assessment Page
  app/javascript/Application/components/Assessment/Domain.test.js
  app/javascript/Application/components/Assessment/DomainPanelSummary.js
  app/javascript/Application/components/Assessment/style.sass
Labels: minor

#685 Small unit test refactors
  app/javascript/Application/components/Assessment/Domain.js
  app/javascript/Application/components/Assessment/Domain.test.js
  app/javascript/Application/components/Assessment/DomainPanelSummary.js
  app/javascript/Application/components/Assessment/DomainPanelSummary.test.js
  app/javascript/Application/components/common/DateField.test.js
Labels: patch

#689 Cans 1030 test fix
  spec/page_objects/assessment_form.rb
Labels: minor

#690 CANS-1183: Update the "Assessment Conducted By" field to add Accessibility Labels
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConductedBy.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConductedBy.test.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConductedByNameField.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConductedByNameField.test.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConductedByRole.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConductedByRole.test.js
  app/javascript/Application/components/Assessment/style.sass
  spec/a11y/a11y_spec.rb
Labels: A11y, minor

#691 Remove assessment from AssessmentOptions props
  app/javascript/Application/components/Assessment/AssessmentFormHeader.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/AssessmentOptions.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/AssessmentOptions.test.js
Labels: patch

#687 CANS-1087 Print Comparison Over Time Table and Graph
  .eslintrc.js
  app/javascript/Application/components/Client/AssessmentComparison/AssessmentComparison.js
  app/javascript/Application/components/Client/AssessmentComparison/AssessmentComparison.test.js
  app/javascript/Application/components/Client/AssessmentComparison/AssessmentComparisonData.mock.js
  app/javascript/Application/components/Client/AssessmentComparison/AssessmentComparisonHelper.js
  app/javascript/Application/components/Client/AssessmentComparison/AssessmentComparisonHelper.test.js
  app/javascript/Application/components/Client/AssessmentComparison/AssessmentComparisonLoadingBoundary.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryLoadingBoundary.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistoryLoadingBoundary.test.js
  app/javascript/Application/components/Client/Client.js
  app/javascript/Application/components/Client/Client.test.js
  app/javascript/Application/components/Client/ClientAssessmentStatistics.js
  app/javascript/Application/components/Client/client.mock.js
  app/javascript/Application/components/Print/PrintStyles.js
  app/javascript/Application/components/Print/printClient/PrintClient.js
  app/javascript/Application/components/Print/printClient/PrintClient.test.js
  app/javascript/Application/components/Print/printClient/PrintClientAssessmentComparison.js
  app/javascript/Application/components/Print/printClient/PrintClientAssessmentComparison.test.js
  app/javascript/Application/components/Print/printClient/PrintClientHelper.js
  app/javascript/Application/components/Print/printClient/PrintClientHelper.test.js
  app/javascript/Application/components/Print/printClient/PrintClientHistory.js
  app/javascript/Application/components/Print/printClient/PrintClientHistory.test.js
  app/javascript/Application/components/Print/printClient/PrintClientInfo.js
  app/javascript/Application/components/Print/printClient/PrintClientInfo.test.js
  app/javascript/Application/components/Print/printClient/PrintClientStyle.js
  app/javascript/Application/components/Print/printClient/PrintComparisonData.mock.js
  app/javascript/Application/components/Print/printClient/PrintComparisonGraph.js
  app/javascript/Application/components/Print/printClient/PrintComparisonGraph.test.js
  app/javascript/Application/components/Print/printClient/PrintComparisonTable.js
  app/javascript/Application/components/Print/printClient/PrintComparisonTable.test.js
  app/javascript/Application/components/pages/ChildProfilePageInner.js
  app/javascript/Application/components/pages/ChildProfilePageInner.test.js
Labels: minor

#688 Cans 1177 accessibility fix
  app/javascript/Application/components/Assessment/AssessmentFormHeader.js
  app/javascript/Application/components/Assessment/Domain.js
  app/javascript/Application/components/Assessment/Domain.test.js
  app/javascript/Application/components/Assessment/DomainScore.js
  app/javascript/Application/components/Assessment/style.sass
  app/javascript/Application/components/Header/PageHeaderButtonsBuilder.js
  app/javascript/Application/components/Header/style.sass
  app/javascript/Application/components/Search/SearchContainer.js
  app/javascript/Application/components/Search/SearchContainer.test.js
  app/javascript/Application/components/Search/style.sass
  app/javascript/Application/styles/global/colors.sass
  spec/page_objects/assessment_form.rb
Labels: patch

#692 Assessment prop is removed from conducted by component
  app/javascript/Application/components/Assessment/AssessmentFormHeader.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConductedBy.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConductedBy.test.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConductedByNameField.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConductedByNameField.test.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConductedByRole.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConductedByRole.test.js
Labels: minor, refactoring

#693 Small Print requirement change: Remove caregiver name from domain comment
  app/javascript/Application/components/Print/printAssessment/PrintDomain.js
  app/javascript/Application/components/Print/printAssessment/PrintDomain.test.js
Labels: patch

#694 CANS-1087: minor styling fixes for Client page print
  app/javascript/Application/components/Print/printClient/PrintClientHistory.js
  app/javascript/Application/components/Print/printClient/PrintClientStyle.js
  app/javascript/Application/components/Print/printClient/PrintComparisonGraph.js
Labels: patch
