Repository ca-cwds/cans, pull requests merged in 2019-03, with the labels that each got.

#550 CANS-1005 Assessment comparison
  app/controllers/api/clients_controller.rb
  app/javascript/Application/components/Assessment/Assessment.js
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/AssessmentSummary/DomainHelper.js
  app/javascript/Application/components/Assessment/AssessmentSummary/SummaryGrid.js
  app/javascript/Application/components/Assessment/BottomCollapseIcon.test.js
  app/javascript/Application/components/Assessment/DomainItemList.js
  app/javascript/Application/components/Assessment/Item/Item.js
  app/javascript/Application/components/Assessment/index.js
  app/javascript/Application/components/Client/AssessmentComparison/AssessmentComparison.js
  app/javascript/Application/components/Client/AssessmentComparison/AssessmentComparison.test.js
  app/javascript/Application/components/Client/AssessmentComparison/AssessmentComparisonLoadingBoundary.js
  app/javascript/Application/components/Client/AssessmentComparison/AssessmentComparisonLoadingBoundary.test.js
  app/javascript/Application/components/Client/AssessmentComparison/ComparisonInnerTable.js
  app/javascript/Application/components/Client/AssessmentComparison/ComparisonInnerTable.test.js
  app/javascript/Application/components/Client/AssessmentComparison/ComparisonOuterTable.js
  app/javascript/Application/components/Client/AssessmentComparison/ComparisonOuterTable.test.js
  app/javascript/Application/components/Client/AssessmentComparison/ComparisonOuterTableExpander.js
  app/javascript/Application/components/Client/AssessmentComparison/ComparisonOuterTableExpander.test.js
  app/javascript/Application/components/Client/AssessmentComparison/ComparisonOuterTableHeader.js
  app/javascript/Application/components/Client/AssessmentComparison/ComparisonOuterTableHeader.test.js
  app/javascript/Application/components/Client/AssessmentComparison/comparisonHelper.js
  app/javascript/Application/components/Client/AssessmentComparison/comparisonHelper.test.js
  app/javascript/Application/components/Client/AssessmentComparison/style.sass
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistory.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistory.test.js
  app/javascript/Application/components/Client/Client.helper.js
  app/javascript/Application/components/Client/Client.helper.test.js
  app/javascript/Application/components/Client/Client.js
  app/javascript/Application/components/Client/Client.service.js
  app/javascript/Application/components/Client/Client.service.test.js
  app/javascript/Application/components/Client/Client.test.js
  app/javascript/Application/components/Client/ClientAssessmentStatistics.js
  app/javascript/Application/components/Client/ClientAssessmentStatistics.test.js
  app/javascript/Application/components/Client/RecordsModeSwitchButton.js
  app/javascript/Application/components/Client/RecordsModeSwitchButton.test.js
  app/javascript/Application/components/Client/style.sass
  app/javascript/Application/components/Print/PrintAssessment.js
  app/javascript/Application/components/common/I18n.service.js
  app/javascript/Application/components/common/I18n.service.test.js
  app/javascript/Application/components/common/I18nHelper.js
  app/javascript/Application/components/common/I18nHelper.test.js
  app/javascript/Application/components/common/index.js
  config/routes.rb
  lib/clients/clients_repository.rb
  spec/controllers/api/clients_controller_spec.rb
  spec/lib/clients/clients_repository_spec.rb
Labels: minor

#554 CANS-1072 Fix for Caregiver domain total when switching age range
  app/javascript/Application/components/Assessment/Domain.js
  app/javascript/Application/components/Assessment/DomainScoreHelper.js
  app/javascript/Application/components/Assessment/DomainScoreHelper.test.js
Labels: minor

#557 CANS-1070: change log and print button bug fix
  app/javascript/Application/components/Assessment/AssessmentChangelogLink.js
  app/javascript/Application/components/Assessment/AssessmentChangelogLink.test.js
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Header/PageHeaderButtons/PrintButton.js
  app/javascript/Application/components/Header/PageHeaderButtons/PrintButton.test.js
  app/javascript/Application/components/common/PageLockService.js
  app/javascript/Application/components/common/PageLockService.test.js
  app/javascript/Application/components/common/UnsavedDataWarning.js
  app/javascript/Application/components/common/UnsavedDataWarning.test.js
Labels: bug, minor

#559 Patch: Try to make the regression test more stable.
  spec/page_objects/assessment_form.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: patch

#556 CANS-1052-Implemented Sorting for DOB in client list card
  app/javascript/Application/components/Client/ClientSocialWorkerCardTemplate.js
  app/javascript/Application/components/Client/ClientSocialWorkerCardTemplate.test.js
  app/javascript/Application/components/Client/ClientSocialWorkerCardTemplateHelper.js
  app/javascript/Application/components/Client/ClientSocialWorkerCardTemplateHelper.test.js
Labels: minor

#561 Patch:Fixing Comparison component render warning ( reverse to Fragment approaching )
  app/javascript/Application/components/Client/AssessmentComparison/AssessmentComparison.js
  app/javascript/Application/components/Client/AssessmentComparison/AssessmentComparison.test.js
  app/javascript/Application/components/Client/Client.test.js
  app/javascript/Application/components/Client/ClientAssessmentStatistics.js
Labels: patch

#562 Update eslint-plugin-react
  app/javascript/Application/components/Assessment/AssessmentRecordStatus.js
  app/javascript/Application/components/Assessment/Domain.js
  app/javascript/Application/components/Assessment/Item/Item.js
  app/javascript/Application/components/Assessment/Item/Item.test.js
  app/javascript/Application/components/Assessment/Item/ItemInner.js
  app/javascript/Application/components/Assessment/Item/ItemInner.test.js
  app/javascript/Application/components/Client/AssessmentComparison/AssessmentComparisonLoadingBoundary.js
  app/javascript/Application/components/Client/AssessmentComparison/AssessmentComparisonLoadingBoundary.test.js
  app/javascript/Application/components/Client/ClientAssessmentStatistics.js
  app/javascript/Application/components/Search/ClientSearch/QueryResults/Results.js
  yarn.lock
Labels: patch

#563 Upgrading React
  legal/licenses.csv
  package.json
  yarn.lock
Labels: minor

#558 Refactor: new assessment to be created on the back end
  app/controllers/api/clients_controller.rb
  app/javascript/Application/components/Assessment/Assessment.service.js
  app/javascript/Application/components/Assessment/Assessment.service.test.js
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  config/routes.rb
  docker-compose.ci.yml
  docker-compose.yml
  lib/clients/clients_repository.rb
  spec/controllers/api/clients_controller_spec.rb
  spec/lib/clients/clients_repository_spec.rb
Labels: minor

#564 Instrument refactor PR#558 follow up clean up commit
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/assessment.mocks.test.js
Labels: patch

#565 CANS-1014: swap item 7 & 8
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConfidentialityAlert.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConfidentialityAlert.test.js
  app/javascript/Application/components/Assessment/assessment.mocks.test.js
  app/javascript/Application/components/Print/PrintAssessment.js
  app/javascript/Application/components/common/ConfidentialityWarning.js
  spec/page_objects/assessment_form.rb
Labels: patch

#567 CANS-1023-DisbleStaffNameIfZeroClients
  app/javascript/Application/components/Staff/StaffNameLink.js
  app/javascript/Application/components/Staff/StaffNameLink.test.js
Labels: minor

#569 CANS-1084: Save button disabled inside modal window for unsavable Assessments
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/common/UnsavedDataWarning.js
  app/javascript/Application/components/common/UnsavedDataWarning.test.js
  app/javascript/Application/styles/global/modal-styles.sass
Labels: patch

#572 Update regression test after switching items
  docker-compose.ci.yml
  docker-compose.yml
  spec/page_objects/assessment_form.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: patch

#570 FIT-404 Apply the new shared library for code quality checks
  Jenkinsfile
Labels: patch

#573 Fit 404 apply shared library for code quality checks
  Jenkinsfile
Labels: patch

#571 CANS-842. Reassessment modal
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Assessment/AssessmentHelper.test.js
  app/javascript/Application/components/Assessment/ReassessmentModal.js
  app/javascript/Application/components/Assessment/ReassessmentModal.test.js
  app/javascript/Application/components/Assessment/assessment.mocks.test.js
  app/javascript/Application/components/Layout/FullWidthLayout.js
  app/javascript/Application/components/Layout/FullWidthLayout.test.js
  app/javascript/Application/components/pages/AssessmentChangelogPageInner.js
  app/javascript/Application/components/pages/AssessmentPageInner.js
  app/javascript/Application/components/pages/AssessmentPageInner.test.js
  app/javascript/Application/components/pages/ChildListPage.js
  app/javascript/Application/components/pages/ChildProfilePageInner.js
  app/javascript/Application/components/pages/SearchPage.js
  app/javascript/Application/components/pages/StaffListPage.js
  app/javascript/Application/components/pages/SubordinateProfilePageInner.js
  app/javascript/Application/styles/global/cwds-conflict-fixes.sass
  app/javascript/Application/styles/global/modal-styles.sass
  docker-compose.ci.yml
  docker-compose.yml
  spec/a11y/a11y_spec.rb
  spec/helpers/assessment_helper.rb
  spec/page_objects/assessment_form.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: minor

#576 CANS-1082 Add Trend Icons on CANS Assessment Compare over time table
  app/javascript/Application/components/Client/AssessmentComparison/AssessmentComparison.test.js
  app/javascript/Application/components/Client/AssessmentComparison/ComparisonInnerTable.js
  app/javascript/Application/components/Client/AssessmentComparison/ComparisonInnerTable.test.js
  app/javascript/Application/components/Client/AssessmentComparison/style.sass
Labels: minor

#574 CANS-870: Reminder to save when user uses the keyboard shortcut to navigate backwards or forwards
  app/javascript/Application/components/common/PageLockService.js
  app/javascript/Application/components/common/PageLockService.test.js
  app/javascript/Application/components/common/UnsavedDataWarning.js
  app/javascript/Application/components/common/UnsavedDataWarning.test.js
  app/javascript/Application/util/common.js
  app/javascript/Application/util/common.test.js
  spec/regression/case_worker_scenarios_spec.rb
Labels: minor

#578 Cans-1004 Added background color on assessment item rating form
  app/javascript/Application/components/Assessment/Item/ItemDescription.js
  app/javascript/Application/components/Assessment/Item/ItemDescriptionRating.js
  app/javascript/Application/components/Assessment/Item/ItemInner.js
  app/javascript/Application/components/Assessment/Item/style.sass
  app/javascript/Application/components/Assessment/style.sass
  app/javascript/Application/styles/global/colors.sass
Labels: minor

#577 CANS-1078. Reassessment data is carried over
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Assessment/AssessmentHelper.test.js
  spec/regression/case_worker_scenarios_spec.rb
Labels: minor

#575 CANS-53 Comparison graph & CANS-1081 Comparison table upgrade
  app/controllers/api/clients_controller.rb
  app/javascript/Application/components/Assessment/AssessmentFormHeader.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader.test.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/style.sass
  app/javascript/Application/components/Client/AssessmentComparison/AssessmentComparison.js
  app/javascript/Application/components/Client/AssessmentComparison/AssessmentComparison.test.js
  app/javascript/Application/components/Client/AssessmentComparison/AssessmentComparisonLoadingBoundary.js
  app/javascript/Application/components/Client/AssessmentComparison/AssessmentComparisonLoadingBoundary.test.js
  app/javascript/Application/components/Client/AssessmentComparison/ComparisonAgeSwitchButtonGroup.js
  app/javascript/Application/components/Client/AssessmentComparison/ComparisonAgeSwitchButtonGroup.test.js
  app/javascript/Application/components/Client/AssessmentComparison/comparisonGraph/ComparisonGraph.js
  app/javascript/Application/components/Client/AssessmentComparison/comparisonGraph/ComparisonGraph.test.js
  app/javascript/Application/components/Client/AssessmentComparison/comparisonGraph/ComparisonGraphInner.js
  app/javascript/Application/components/Client/AssessmentComparison/comparisonGraph/ComparisonGraphInner.test.js
  app/javascript/Application/components/Client/AssessmentComparison/comparisonGraph/comparisonGraphDataTransformations.js
  app/javascript/Application/components/Client/AssessmentComparison/comparisonGraph/comparisonGraphDataTransformations.test.js
  app/javascript/Application/components/Client/AssessmentComparison/comparisonHelper.js
  app/javascript/Application/components/Client/AssessmentComparison/comparisonTable/ComparisonInnerTable.js
  app/javascript/Application/components/Client/AssessmentComparison/comparisonTable/ComparisonInnerTable.test.js
  app/javascript/Application/components/Client/AssessmentComparison/comparisonTable/ComparisonOuterTable.js
  app/javascript/Application/components/Client/AssessmentComparison/comparisonTable/ComparisonOuterTable.test.js
  app/javascript/Application/components/Client/AssessmentComparison/comparisonTable/ComparisonOuterTableExpander.js
  app/javascript/Application/components/Client/AssessmentComparison/comparisonTable/ComparisonOuterTableExpander.test.js
  app/javascript/Application/components/Client/AssessmentComparison/comparisonTable/ComparisonOuterTableHeader.js
  app/javascript/Application/components/Client/AssessmentComparison/comparisonTable/ComparisonOuterTableHeader.test.js
  app/javascript/Application/components/Client/AssessmentComparison/comparisonTable/comparisonTableHelper.js
  app/javascript/Application/components/Client/AssessmentComparison/comparisonTable/comparisonTableHelper.test.js
  app/javascript/Application/components/Client/AssessmentComparison/style.sass
  app/javascript/Application/components/Client/Client.helper.js
  app/javascript/Application/components/Client/Client.helper.test.js
  app/javascript/Application/components/Client/Client.service.js
  app/javascript/Application/components/Client/Client.service.test.js
  app/javascript/Application/components/Client/RecordsModeSwitchButton.js
  app/javascript/Application/components/Client/RecordsModeSwitchButton.test.js
  app/javascript/Application/components/common/AgeRangeSwitch.js
  app/javascript/Application/components/common/AgeRangeSwitch.test.js
  app/javascript/Application/components/common/style.sass
  legal/licenses.csv
  lib/clients/clients_repository.rb
  package.json
  spec/controllers/api/clients_controller_spec.rb
  spec/lib/clients/clients_repository_spec.rb
  yarn.lock
Labels: minor

#580 CANS-1014: substance use warnings text updated to use dynamic item id for 7/8
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainerInner.js
  app/javascript/Application/components/Assessment/AssessmentContainerInner.test.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader.test.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConfidentialityAlert.js
  app/javascript/Application/components/Assessment/AssessmentFormHeader/ConfidentialityAlert.test.js
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Assessment/AssessmentHelper.test.js
  app/javascript/Application/components/Assessment/WarningShow.js
  app/javascript/Application/components/Assessment/WarningShow.test.js
  app/javascript/Application/components/Assessment/assessment.mocks.test.js
  app/javascript/Application/components/Print/PrintAssessment.js
  app/javascript/Application/components/Print/PrintAssessment.test.js
  app/javascript/Application/components/common/ConfidentialityWarning.js
  app/javascript/Application/components/common/ConfidentialityWarning.test.js
Labels: patch

#579 CANS-838-AddCANSButtonTextToggle
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Assessment/AssessmentHelper.test.js
  app/javascript/Application/components/Assessment/index.js
  app/javascript/Application/components/Client/AddCansButton.js
  app/javascript/Application/components/Client/AddCansButton.test.js
  app/javascript/Application/components/Client/AddCansLink.js
  app/javascript/Application/components/Client/AddCansLink.test.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistory.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistory.test.js
  app/javascript/Application/components/Client/style.sass
  spec/helpers/assessment_helper.rb
  spec/page_objects/client_profile.rb
Labels: minor

#582 CANS-870: Reminder to save when user uses the keyboard shortcut to navigate backwards or forwards (bug fix)
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/common/PageLockService.js
  app/javascript/Application/components/common/PageLockService.test.js
  spec/regression/case_worker_scenarios_spec.rb
Labels: bug, minor

#584 Tiny refactoring as per PR comment
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Assessment/AssessmentHelper.test.js
Labels: patch

#583 CANS-1086: upgrade to cwds/components 1.1.1
  app/javascript/Application/components/Assessment/AssessmentActionsEllipsis.js
  app/javascript/Application/components/Assessment/AssessmentActionsEllipsis.test.js
  app/javascript/Application/components/Assessment/BottomCollapseIcon.js
  app/javascript/Application/components/Assessment/BottomCollapseIcon.test.js
  app/javascript/Application/components/Assessment/Domain.js
  app/javascript/Application/components/Assessment/DomainCommentAccordion.js
  app/javascript/Application/components/Assessment/Item/ItemHeader.js
  app/javascript/Application/components/Assessment/Item/ItemHeader.test.js
  app/javascript/Application/components/Client/AssessmentComparison/comparisonTable/ComparisonOuterTableExpander.js
  app/javascript/Application/components/Client/AssessmentComparison/comparisonTable/ComparisonOuterTableExpander.test.js
  app/javascript/Application/components/Layout/FullWidthLayout.js
  app/javascript/Application/components/Layout/FullWidthLayout.test.js
  app/javascript/Application/components/Search/ClientSearch/QueryResults/PersonSuggestion/PersonSuggestion.js
  app/javascript/Application/components/common/DataGridHeader.js
  app/javascript/Application/components/common/DataGridHeader.test.js
  app/javascript/Application/components/common/TimeoutWarning.js
  app/javascript/Application/index.js
  app/javascript/Application/util/constants.js
  legal/licenses.csv
  package.json
  spec/helpers/assessment_helper.rb
  yarn.lock
Labels: minor

#581 Cans 844 Review Reassessment
  app/javascript/Application/components/Assessment/Assessment.js
  app/javascript/Application/components/Assessment/Assessment.test.js
  app/javascript/Application/components/Assessment/Domain.js
  app/javascript/Application/components/Assessment/Domain.test.js
  app/javascript/Application/components/Assessment/style.sass
  app/javascript/Application/styles/global/cwds-conflict-fixes.sass
  spec/a11y/a11y_spec.rb
  spec/page_objects/assessment_form.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: enhancement, minor

#587 CANS-1078. Fix a bug with item and domain comment collapsing
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Assessment/AssessmentHelper.test.js
  spec/regression/case_worker_scenarios_spec.rb
Labels: bug, patch

#586 CANS-1086: custom ellipses replaced by components library Menu component
  app/javascript/Application/components/Assessment/AssessmentActionsEllipsis.js
  app/javascript/Application/components/Assessment/AssessmentActionsEllipsis.test.js
  app/javascript/Application/components/Assessment/AssessmentActionsMenu.js
  app/javascript/Application/components/Assessment/AssessmentActionsMenu.test.js
  app/javascript/Application/components/Assessment/AssessmentActionsMenuItemChangeLog.js
  app/javascript/Application/components/Assessment/AssessmentActionsMenuItemChangeLog.test.js
  app/javascript/Application/components/Assessment/AssessmentActionsMenuItemDeleteAssessment.js
  app/javascript/Application/components/Assessment/AssessmentActionsMenuItemDeleteAssessment.test.js
  app/javascript/Application/components/Assessment/AssessmentRecordInfo.js
  app/javascript/Application/components/common/style.sass
  spec/page_objects/client_profile.rb
Labels: patch

#585 CANS-1041 Button route to comparison
  app/javascript/Application/components/Client/AssessmentComparison/AssessmentComparison.js
  app/javascript/Application/components/Client/AssessmentComparison/AssessmentComparison.test.js
  app/javascript/Application/components/Client/AssessmentComparison/style.sass
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistory.js
  app/javascript/Application/components/Client/AssessmentHistory/ClientAssessmentHistory.test.js
  app/javascript/Application/components/Client/AssessmentRecordControl.js
  app/javascript/Application/components/Client/AssessmentRecordControl.test.js
  app/javascript/Application/components/Client/Client.helper.js
  app/javascript/Application/components/Client/Client.helper.test.js
  app/javascript/Application/components/Client/Client.js
  app/javascript/Application/components/Client/Client.test.js
  app/javascript/Application/components/Client/ClientAssessmentStatistics.js
  app/javascript/Application/components/Client/ClientAssessmentStatistics.test.js
  app/javascript/Application/components/Client/ClientAssessmentStatisticsHeader.js
  app/javascript/Application/components/Client/ClientAssessmentStatisticsHeader.test.js
  app/javascript/Application/components/Client/RecordsModeSwitchButton.js
  app/javascript/Application/components/Client/RecordsModeSwitchButton.test.js
  app/javascript/Application/components/Client/style.sass
Labels: minor

#589 CANS-1086: styles fix for ellipses menu
  app/javascript/Application/styles/global/cwds-conflict-fixes.sass
  app/javascript/Application/styles/global/global-styles.sass
Labels: patch

#588 CANS-844Fix for Open to review button
  app/javascript/Application/components/Assessment/Assessment.js
  app/javascript/Application/components/Assessment/Assessment.test.js
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Assessment/AssessmentHelper.test.js
  app/javascript/Application/components/Assessment/Domain.js
  app/javascript/Application/components/Assessment/Domain.test.js
  spec/a11y/a11y_spec.rb
  spec/page_objects/assessment_form.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: patch

#590 CANS-1086: style fix for MenuItem link
  app/javascript/Application/styles/global/global-styles.sass
Labels: patch

#592 CANS-844-IE-fix
  app/javascript/Application/components/Assessment/style.sass
Labels: bug, patch

#591 CANS-1038: redact discretion needed items on print
  app/javascript/Application/components/Assessment/assessment.mocks.test.js
  app/javascript/Application/components/Print/PrintAssessment.js
  app/javascript/Application/components/Print/PrintAssessment.test.js
  legal/licenses.csv
  package.json
  yarn.lock
Labels: minor

#598 CC.yml file-lines syntax corrected
  .codeclimate.yml
Labels: patch

#597 CANS-1090 Tooltips don't Disappear
  app/javascript/Application/components/Assessment/Domain.js
  app/javascript/Application/components/Assessment/Domain.test.js
Labels: minor

#595 CANS-1095: UserMenu component refactored using cwds/components components
  app/javascript/Application/components/Header/UserMenu.js
  app/javascript/Application/components/Header/UserMenu.test.js
  app/javascript/Application/styles/global/cwds-conflict-fixes.sass
Labels: patch

#593 CANS-1083 ExpandAllHiddenUntilDomainsReviewed
  app/javascript/Application/components/Assessment/Assessment.js
  app/javascript/Application/components/Assessment/Assessment.test.js
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Assessment/AssessmentHelper.test.js
  app/javascript/Application/components/Assessment/DomainsHeader.js
  app/javascript/Application/components/Assessment/DomainsHeader.test.js
Labels: minor

#596 CANS-1000: Complete modal window reworked
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/AssessmentContainerInner.js
  app/javascript/Application/components/Assessment/AssessmentContainerInner.test.js
  app/javascript/Application/components/Assessment/CompleteModal.js
  app/javascript/Application/components/Assessment/CompleteModal.test.js
  app/javascript/Application/components/Assessment/WarningShow.js
  app/javascript/Application/components/Assessment/WarningShow.test.js
  app/javascript/Application/components/common/ConfidentialityWarning.js
  app/javascript/Application/components/common/ConfidentialityWarning.test.js
  app/javascript/Application/styles/global/cwds-conflict-fixes.sass
  spec/page_objects/sections/app_globals.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: minor

#599 CANS-843 Alert on clicking Use previous ratings
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
Labels: minor

#594 CANS-1089. Complete a Reassessment (or Assessment)
  app/javascript/Application/components/Assessment/Assessment.js
  app/javascript/Application/components/Assessment/Assessment.test.js
  app/javascript/Application/components/Assessment/AssessmentActionsEllipsis.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/AssessmentContainerInner.js
  app/javascript/Application/components/Assessment/AssessmentContainerInner.test.js
  app/javascript/Application/components/Assessment/AssessmentFormFooter.js
  app/javascript/Application/components/Assessment/AssessmentFormFooter.test.js
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Assessment/AssessmentHelper.test.js
  app/javascript/Application/components/Assessment/ChangelogLink.js
  app/javascript/Application/components/Assessment/ChangelogLink.test.js
  app/javascript/Application/components/Assessment/CompleteModal.js
  app/javascript/Application/components/Assessment/Domain.js
  app/javascript/Application/components/Assessment/FormFooter/AssessmentFormFooter.js
  app/javascript/Application/components/Assessment/FormFooter/AssessmentFormFooter.test.js
  app/javascript/Application/components/Assessment/FormFooter/CancelAssessmentButton.js
  app/javascript/Application/components/Assessment/FormFooter/CancelAssessmentButton.test.js
  app/javascript/Application/components/Assessment/FormFooter/CompleteAssessmentButton.js
  app/javascript/Application/components/Assessment/FormFooter/CompleteAssessmentButton.test.js
  app/javascript/Application/components/Assessment/FormFooter/FooterControls.js
  app/javascript/Application/components/Assessment/FormFooter/FooterControls.test.js
  app/javascript/Application/components/Assessment/FormFooter/ReviewConfirmation.js
  app/javascript/Application/components/Assessment/FormFooter/ReviewConfirmation.test.js
  app/javascript/Application/components/Assessment/FormFooter/style.sass
  app/javascript/Application/components/Assessment/ReassessmentModal.js
  app/javascript/Application/components/Assessment/index.js
  app/javascript/Application/components/Assessment/style.sass
  app/javascript/Application/components/Client/AddCansButton.js
  app/javascript/Application/components/Header/UserMenu.js
  app/javascript/Application/components/common/UnsavedDataWarning.js
  app/javascript/Application/styles/global/cwds-conflict-fixes.sass
  app/javascript/Application/styles/global/global-styles.sass
  spec/page_objects/assessment_form.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: minor

#600 CANS-1080. Visual Indicator of Carried Over Ratings
  app/javascript/Application/components/Assessment/Assessment.js
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/AssessmentContainerInner.js
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Assessment/AssessmentHelper.test.js
  app/javascript/Application/components/Assessment/Domain.js
  app/javascript/Application/components/Assessment/Domain.test.js
  app/javascript/Application/components/Assessment/DomainCommentAccordion.js
  app/javascript/Application/components/Assessment/DomainItemList.js
  app/javascript/Application/components/Assessment/DomainItemList.test.js
  app/javascript/Application/components/Assessment/Item/ConfidentialCheckbox.js
  app/javascript/Application/components/Assessment/Item/Item.js
  app/javascript/Application/components/Assessment/Item/Item.test.js
  app/javascript/Application/components/Assessment/Item/ItemBooleanRating.test.js
  app/javascript/Application/components/Assessment/Item/ItemInner.js
  app/javascript/Application/components/Assessment/Item/ItemInner.test.js
  app/javascript/Application/components/Assessment/Item/ItemNaCheckbox.js
  app/javascript/Application/components/Assessment/Item/ItemRating.js
  app/javascript/Application/components/Assessment/Item/ItemRating.test.js
  app/javascript/Application/components/Assessment/Item/ItemRegularRating.test.js
  app/javascript/Application/components/Assessment/Item/ItemStyling.js
  app/javascript/Application/components/Assessment/Item/ItemToolbarControls.js
  app/javascript/Application/components/Assessment/Item/ItemToolbarControls.test.js
  app/javascript/Application/components/Assessment/Item/style.sass
  app/javascript/Application/components/Assessment/style.sass
  spec/regression/case_worker_scenarios_spec.rb
Labels: minor

#601 CANS-1000: regression test stability fix
  app/javascript/Application/components/Assessment/AssessmentContainerInner.js
  legal/licenses.csv
  package.json
  spec/helpers/assessment_helper.rb
  spec/regression/case_worker_scenarios_spec.rb
  yarn.lock
Labels: minor

#603 CANS-1088: Move Domain Level Comments to Domain Footer
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/Domain.js
  app/javascript/Application/components/Assessment/Domain.test.js
  app/javascript/Application/components/Assessment/DomainComment.js
  app/javascript/Application/components/Assessment/DomainComment.test.js
  app/javascript/Application/components/Assessment/DomainCommentAccordion.js
  app/javascript/Application/components/Assessment/DomainCommentAccordion.test.js
  app/javascript/Application/components/Assessment/Item/ItemDescription.test.js
  app/javascript/Application/components/Assessment/style.sass
  app/javascript/Application/components/common/Comment.js
  spec/page_objects/assessment_form.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: minor

#606 CANS-1080. Fix for caregiver domains
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Assessment/AssessmentHelper.test.js
  app/javascript/Application/components/Assessment/DomainItemList.js
  app/javascript/Application/components/Assessment/DomainItemList.test.js
  spec/page_objects/assessment_form.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: patch

#608 CANS-1119 Reassessment confidential Checkboxes defaults to checked
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Assessment/AssessmentHelper.test.js
Labels: bug, minor

#609 CANS-1095: MenuItem logout fixed to use href instead of window.location.assign
  app/javascript/Application/components/Header/UserMenu.js
  app/javascript/Application/components/Header/UserMenu.test.js
  spec/acceptance_helpers/login_helper.rb
Labels: patch

#604 CANS-1096 Reassessment to Age Template Default
  app/javascript/Application/components/Assessment/AssessmentContainer.js
  app/javascript/Application/components/Assessment/AssessmentContainer.test.js
  app/javascript/Application/components/Assessment/AssessmentHelper.js
  app/javascript/Application/components/Assessment/AssessmentHelper.test.js
Labels: enhancement, patch

#610 CANS-1073: Overall Domain Collapse Button
  app/javascript/Application/components/Assessment/Domain.test.js
  app/javascript/Application/components/Assessment/DomainCollapseButton.js
  app/javascript/Application/components/Assessment/DomainCollapseButton.test.js
  app/javascript/Application/components/Assessment/DomainComment.js
  app/javascript/Application/components/Assessment/DomainComment.test.js
  app/javascript/Application/components/Assessment/style.sass
  spec/page_objects/assessment_form.rb
  spec/regression/case_worker_scenarios_spec.rb
Labels: minor

#611 CANS-1103: change log date format updated
  app/javascript/Application/components/Assessment/ChangeLog/ChangeLogDate.js
  app/javascript/Application/components/Assessment/ChangeLog/ChangeLogDate.test.js
  app/javascript/Application/components/Assessment/ChangeLog/PrintChangeLog.test.js
Labels: patch

#612 CANS-1074 Chevron updates on Assessment and Assessment History form
  app/javascript/Application/components/Assessment/Domain.js
  app/javascript/Application/components/Assessment/Domain.test.js
  app/javascript/Application/components/Assessment/Item/ItemHeader.js
  app/javascript/Application/components/Assessment/style.sass
  app/javascript/Application/components/Client/AssessmentComparison/comparisonTable/ComparisonInnerTable.js
  app/javascript/Application/components/Client/AssessmentComparison/comparisonTable/ComparisonInnerTable.test.js
  app/javascript/Application/components/Client/AssessmentComparison/comparisonTable/ComparisonOuterTable.js
  app/javascript/Application/components/Client/AssessmentComparison/comparisonTable/ComparisonOuterTable.test.js
  app/javascript/Application/components/Client/AssessmentComparison/comparisonTable/ComparisonOuterTableExpander.js
  app/javascript/Application/components/Client/AssessmentComparison/comparisonTable/ComparisonOuterTableExpander.test.js
Labels: minor

#614 Stabilize regression test
  spec/regression/case_worker_scenarios_spec.rb
Labels: patch
